### ISSUE TITLE
Context change displayed inconsistently in resources and knowledge graph

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#1038]
## Reproducing the error
1. Create a context:
```json
{
  "@context": {
    "@vocab": "http://example.com/vocab/"
  },
  "@id": "http://example.com/mycontext"
}
```
2. Create a resource
```json
{
  "@context": "http://example.com/mycontext",
  "@id": "http://example.com/myid",
  "field": "value"
}
```
3. Update the context
```json
{
  "@context": {
    "@vocab": "http://example.com/vocab/",
    "field": "http://example.com/myfield"
  },
  "@id": "http://example.com/mycontext"
}
```
4. Fetch the resource in expanded form (omitting the metadata)
```json
{
  "@id": "http://example.com/myid",
  "http://example.com/myfield": "value"
}
```
5. Perform the following SPARQL query on the project
```
SELECT * WHERE { GRAPH <http://example.com/myid/graph>{?s ?p ?o} }
```
The result (omitting the metadata) will be
```
<http://example.com/myid>  <http://example.com/vocab/>  "value"
```

This is inconsistent with the result obtained from point 4.

## Possible solutions
- Store in the primary store the resolved context value at the time of the resource creation and provide a query param to fetch the resource either with current context resolution or with context resolution at creation time
- Add a `rebuildStrategy` on the views where rebuild of views can be triggered when certain resources are created/updated. 
In this particular case, we want to monitor a change on the resource with id chttp://example.com/mycontext. Whenever that change occurs, we will restart the view progress, which in turn will update the resource context in the sparql namespace.

**Comment by pafonta** [comment]
Thank you for documenting it! We opened also a ticket on our side to think about the issue one the Knowledge Graph Modeling side.

**Comment by MFSY** [comment]
Hi @umbreak , @bogdanromanx 

FYI @annakristinkaufmann 

Here is my understanding of the proposal implementation to address this issue:

External Context: A context referenced in a resource (using an IRI) but managed either in a remote project or in the project in which the resource is located.


1. When the user creates or updates a resource then the current state of its external context is fetched and associated with the resource and propagated to the downstream indices (SPARQL, ES).
2. When the external context alone (i.e no change on the resource) changed then:
	- the change is not reflected when the resource is expanded using Nexus DELTA API
	- the change is not propagated to the downstream indices (SPARQL, ES)
3. When the downstream indices (SPARQL, ES) are triggered because of a configuration change, then there is no external context fetching and the latest context state (the last time the resource was created or updated) is propagated.

If my understanding of the proposed implementation is correct, then this is bringing potentially performance improvement as well as protecting a remote change on a context to directly (and silently ?) impact a resource ( sometimes in a bad way as metadata at a given revision are impacted by this). Bounding a resource change with its context refresh is a good idea on that perspective.

This change is not solving though the issue of desynchronisation between a resource and the external context it refers to. The solution seems to be:

* Not to perform non-backward compatible changes on a context. 
* If a non-backward compatible change can't be avoided, then relevant resources need to be updated. It can be good for Nexus Delta to provide a way to (upon demand) automatically refresh resources when external context changes occurs.

**Comment by umbreak** [comment]
The resource can be stored in the following forms for each even:
- original payload
- compacted
- expanded

If the 3 forms are stored on each event, we don't need to perform any context resolution when fetching nor when storing in the triple store. This guarantees immutability of resources.

If a context is updated and the change should be propagated across all the resources, then this will have to be done manually.

**Comment by bogdanromanx** [comment]
Thanks @MFSY, your understanding is correct.

On your comment:
> It can be good for Nexus Delta to provide a way to (upon demand) automatically refresh resources when external context changes occurs.
I think we need to consider in this case the changes to the "conformant" state of the resource wrt its schema, because changes in the context may make a resource fail validation. I would argue that an API for this would have to be exposed per resource (not for the entire project) and the validation would need to be re-executed. Something along the lines of:
```
DELETE /v1/resources/{org}/{proj}/_/{resource_id}/resolution
or
DELETE /v1/resources/{org}/{proj}/_/{resource_id}/context
or
DELETE /v1/resources/{org}/{proj}/_/{resource_id}/cache
```
The call would trigger a new validation: if the validation succeeds, the resource is automatically updated with the new compacted and expanded representation yielding a new revision; if the validation fails, the caller would be informed that the validation has failed and has the opportunity to perform a normal update instead correcting the validation issue.
Thoughts?

**Comment by bogdanromanx** [comment]
Fixed with the storage of compacted and expanded forms for all events in v1.5.
