### ISSUE TITLE
Default page description for a resource listed in a dashboard

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus#1089]
When I create a dashboard without selecting a plugin (because the one available are not applicable or none was available), a "No plugins configured" message is displayed.

It would be good to have a default page description (sort of default plugin) for resources when a plugin is not selected.

One example of default page description (default plugin) could be the one displayed for every resource within Nexus-web.

"No plugins configured" message:

<img width="1603" alt="Screenshot 2020-03-10 at 18 08 50" src="https://user-images.githubusercontent.com/2990875/76339610-9e92fa80-62fa-11ea-9719-f913be326994.png">

Dashboard building panel:

<img width="1225" alt="Screenshot 2020-03-10 at 18 09 14" src="https://user-images.githubusercontent.com/2990875/76339655-ae124380-62fa-11ea-80fb-b80ea150f7c0.png">

**Comment by MFSY** [comment]
Upon loading the page, there is a warning message display on top.

<img width="1177" alt="Screenshot 2020-03-11 at 09 08 33" src="https://user-images.githubusercontent.com/2990875/76395783-587c7c00-6378-11ea-8b00-44da5a651284.png">

**Comment by adulbrich** [comment]
@MFSY Since 1.3.2, users with write privilege will always see the admin plugin. If only the admin is present, it will be expanded. If other plugins are present and user has write privilege, the admin plugin will be collapsed. If no plugin are mapped and the user does not have write privilege, he currently sees nothing. We will improve on this with https://github.com/BlueBrain/nexus/issues/1123.
