### ISSUE TITLE
Design a CQL based schema for the primary store

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#1115]
Provide a design which covers the following aspects:
- keyspace schemas
- support for Nexus metadata at a column level
- queries: Events-by-id
- queries: all events
- queries: Events-by org
- queries: Events-by project
- queries: Events-by type (supported Nexus types and mind types)
- queries Events by combination of the previous ones
- queries-goal: Support some of the API listings through the primary store
- snapshots (event sourcing)
- export
- persistence-id deletion support

**Comment by wwajerowicz** [comment]
I've been looking into the possible table schemas for this, but I'm not sure if it's possible to create a single table schema that meets all the above expectations.
It seems that using the Cassandra indices could be helpful here ([Cassandra docs](https://docs.datastax.com/en/cql-oss/3.3/cql/cql_using/useWhenIndex.html)), as the values of the indexed fields should have rather low cardinality(orgs, projects, types).

Considering  these tables:

```
CREATE TABLE messages_v14 ( 
  proj_id text,
  org_id text,
  resource_id text,
  sequence_nr bigint, 
  timestamp timeuuid,
  timebucket text,
  event blob,
  tags set<text>,
  PRIMARY KEY ((org_id, proj_id, resource_id), timestamp, sequence_nr) 
) WITH CLUSTERING ORDER BY (timestamp ASC, sequence_nr ASC);
```

```
CREATE INDEX tags_idx ON messages_v14 ( tags );
```    
   
```
CREATE TABLE tag_views_v14 (
    timebucket bigint,
    proj_id text,
    org_id text,
    resource_id text,
    timestamp timeuuid,
    sequence_nr bigint,
    event blob,
    tags set<text>,
    PRIMARY KEY (timebucket, timestamp, proj_id, org_id, resource_id,sequence_nr)
) WITH CLUSTERING ORDER BY (timestamp ASC, proj_id ASC, org_id ASC, resource_id ASC, sequence_nr ASC);
```


```
CREATE INDEX tag_views_idx ON tag_views_v14 ( tags );
```

However, so far I was not able to achieve both at the same time:
  - keeeping the order of events
  - being able to filter by more than one of: organization, project and type


Just using `messages_v14` table with index, it is possible to fetch by one of the `tags`, but the order of results is not guaranteed.



The `tag_views_v14` is based on what `akka-persistence-cassandra` is currently using. We could partition by `timebucket` and sort by `timestamp` and on top of that use one tag to filter using query like that:

```
SELECT timebucket,timestamp FROM tag_views_v14 WHERE timebucket=1582538400000 AND tags CONTAINS ?;
```

The only advantage of this solution over `akka-persistence-cassandra` is that the event is not repeated in the tags table for each tag.

We could rearrange primary key in the tags table  to `PRIMARY KEY (timebucket, ,  org_id, proj_id, timestamp, resource_id,sequence_nr)` and then we could query by organization, project and one tag(which could be the type). However, for queries without oranization and/or project we would lose the ordering of events by timestamp.

Having two versions of the `tag_views` table with two different clustering column orders, could in theory solve our usecase, but we still need some process to index it to those tables.

Another drawback is that, if there are a lot of events ingested quickly, a single partition for that timebucket could be quite big. But that's the case with our current implementation as well, since we tag every event with `event` tag.

@umbreak @bogdanromanx any thoughts and ideas?

**Comment by umbreak** [comment]
akka-persistence-cassandra had the concept of set<tag> cause they're a generic implementation. We don't need that. We need other columns for deprecated, created, updated, ... (metadata).

That said, I see how this is still not helping the design to meet all the requirements we set

**Comment by bogdanromanx** [comment]
I agree that we don't need tags if everything is expanded as a column value (org, proj, primary type etc.) and that we need (at least part of) the metadata to be added as column values.

Given the limitations in query capabilities, we need a primary table, a set of indices and secondary tables that will allow additional queries. For single valued columns that need to be indexed in conjunction with others, the use of materialized views would allow for better performance compared to secondary indices at the expense of space.

We also need to support some form of snapshotting for persistent entities that suffer many updates to remove the network pressure and improve latency.

I think it's important to figure out what we can support without managing an index off-process (within the service) and for the remaining cases how we can handle maintaining a progress, latency until being fully consistent and healing strategies.

**Comment by wwajerowicz** [comment]
I think `akka-persistence-cassandra` moved away from materialized views, because they considered them unstable: https://github.com/akka/akka-persistence-cassandra/issues/247
Yes, I'll move metadata each to it's own field in the table.
But still, even with indexing/materialized views, we won't be able to use arbitrary combination of fields to filter by.

**Comment by umbreak** [comment]
Yes, also seen the same sort of message, trying to avoid materialized views in: https://stackoverflow.com/questions/48974287/cassandra-materialized-views-impact#answer-48977288

**Comment by wwajerowicz** [comment]
For the events I think we could use a messages table like this:

```
CREATE TABLE messages_v14 ( 
  proj_id text,
  org_id text,
  resource_id text,
  sequence_nr bigint, 
  timestamp timeuuid,
  timebucket text,
  source blob,
  deprecated boolean,
  createdAt timestamp,
  updatedAt timestamp,
  createdBy text,
  updatedBy text,
  event_type text,
  types set<text>,
  PRIMARY KEY ((org_id, proj_id, resource_id), timestamp, sequence_nr) 
) WITH CLUSTERING ORDER BY (timestamp ASC, sequence_nr ASC);
```
and two options

 Either we create a view table with indices:  
```
CREATE TABLE timebucket_views_v14 (
    timebucket bigint,
    proj_id text,
    org_id text,
    resource_id text,
    timestamp timeuuid,
    sequence_nr bigint,
    source blob,
    createdAt timestamp,
    updatedAt timestamp,
    createdBy text,
    updatedBy text,
    event_type text,
    types set<text>,
    PRIMARY KEY (timebucket, timestamp, proj_id, org_id, resource_id,sequence_nr)
) WITH CLUSTERING ORDER BY (timestamp ASC, proj_id ASC, org_id ASC, resource_id ASC, sequence_nr ASC);

CREATE INDEX types_idx ON tag_views_v14 ( types );

CREATE INDEX event_type_idx ON tag_views_v14 ( event_type );
```

Or we create a new table instead of each index:

```
CREATE TABLE timebucket_tag_views_v14 (
    timebucket bigint,
    type text,
    proj_id text,
    org_id text,
    resource_id text,
    timestamp timeuuid,
    sequence_nr bigint,
    source blob,
    createdAt timestamp,
    updatedAt timestamp,
    createdBy text,
    updatedBy text,
    event_type text,
    types set<text>,
    PRIMARY KEY ((timebucket, type), timestamp, proj_id, org_id, resource_id,sequence_nr)
) WITH CLUSTERING ORDER BY (timestamp ASC, proj_id ASC, org_id ASC, resource_id ASC, sequence_nr ASC);



CREATE TABLE timebucket_event_type_views_v14 (
    timebucket bigint,    
    proj_id text,
    org_id text,
    resource_id text,
    timestamp timeuuid,
    sequence_nr bigint,
    source blob,
    createdAt timestamp,
    updatedAt timestamp,
    createdBy text,
    updatedBy text,
    event_type text,
    types set<text>,
    PRIMARY KEY ((timebucket, event_type), timestamp, proj_id, org_id, resource_id,sequence_nr)
) WITH CLUSTERING ORDER BY (timestamp ASC, proj_id ASC, org_id ASC, resource_id ASC, sequence_nr ASC);
```

In both cases we would need to duplicate each table with different clustering keys in order to support queries with and without organization/project.

In both cases, we would have to write an indexing strategy similar to `akka-persistence-cassandra`.

For snapshots we could do something like this
```
CREATE TABLE snapshots_v14 ( 
  proj_id text,
  org_id text,
  resource_id text,
  revision bigint, 
  timestamp timeuuid,
  state blob,
  deprecated boolean,
  createdAt timestamp,
  updatedAt timestamp,
  createdBy text,
  updatedBy text,
  types set<text>
  PRIMARY KEY ((org_id, proj_id, resource_id)) 
) WITH CLUSTERING ORDER BY (timestamp ASC, sequence_nr ASC);
```

**Comment by umbreak** [comment]
Do we still need `sequence_nr`? Seems to me `sequence_nr` and `revision` to be the same? What do we gain having both?

Could we, with those indices on the view tables perform the following queries?
- Query all events in a project by `event_type` and `deprecated` (for example)
- Query all events in all projects by `event_type` and `deprecated` (for example)

**Comment by wwajerowicz** [comment]
you're right, we can remove `sequence_nr` if we have `revision`.

> Could we, with those indices on the view tables perform the following queries?
> 
> Query all events in a project by event_type and deprecated (for example)
> Query all events in all projects by event_type and deprecated (for example)

If we added one of those(event_type or deprecated) to the clustering key, we could possibly do that, but we still need two tables: one for queries for all projects and one for queries for a single project/org.

**Comment by wwajerowicz** [comment]
In order to support queries by org/proj and type we would need to create quite a few variations of the following table:
```
CREATE TABLE timebucket_type_events_v14 (
    timebucket bigint,
    type text,
    proj_id text,
    org_id text,
    resource_id text,
    timestamp timeuuid,
    sequence_nr bigint,
    source blob,
    createdAt timestamp,
    updatedAt timestamp,
    createdBy text,
    updatedBy text,
    event_type text,
    types set<text>,
    PRIMARY KEY ((timebucket, type), timestamp,  org_id, proj_id, resource_id,sequence_nr)
) WITH CLUSTERING ORDER BY (timestamp ASC);
```

- to support streaming of all events we'd need `PRIMARY KEY (timebucket, timestamp,  org_id, proj_id, resource_id,sequence_nr)` and `CLUSTERING ORDER BY (timestamp ASC)`
- to support streaming of all events by type we'd need `PRIMARY KEY ((timebucket, type), timestamp,  org_id, proj_id, resource_id,sequence_nr)` and `CLUSTERING ORDER BY (timestamp ASC)`
- to support streaming of all events for an organization we'd need `PRIMARY KEY ((timebucket, org_id), timestamp, proj_id, resource_id,sequence_nr)` and `CLUSTERING ORDER BY (timestamp ASC)`
- to support streaming of all events for a project we'd need `PRIMARY KEY ((timebucket, proj_id), timestamp, org_id, resource_id,sequence_nr)` and `CLUSTERING ORDER BY (org_id ASC, proj_id ASC, timestamp ASC)`
- to support streaming of all events for an organization and type we'd need `PRIMARY KEY ((timebucket, org_id, type), timestamp, proj_id, resource_id,sequence_nr)` and `CLUSTERING ORDER BY ( timestamp ASC)`
- to support streaming of all events for a project and type we'd need `PRIMARY KEY ((timebucket, type,proj_id), timestamp, org_id, resource_id,sequence_nr)` and `CLUSTERING ORDER BY (timestamp ASC)`

This gives us 3 + 3x types_count writes for each event. Our current `akka-persistence-cassandra` gives 3 + 1 x types_count writes, but only gives us possibility to read by one of organization, project and type.


If we try to use the index for types, we can remove all the variations with `type` in the partition key and create and index on the `types` column.
This would give use 3 writes per event(+ overhead of Cassandra indexing).
