### ISSUE TITLE
 Resources created cannot be fetched by API calls or Web frontend, docker-compose installation. v1.3.3

### ISSUE THREAD

**Issue by am4nu** [BlueBrain/nexus#1182]
Cannot load any resources created before in the project both in web and API calls. Tested in both the server and local, none of them works. We doubt that there is some issue with the docker image itself. To reproduce this issue, follow steps:

Create an organization and a project under it.   

Create a resource under the project 

Refresh web page to reload resources under the project, no resource shows up

Fetch resources under the project by API, also no resource inside project
`# GET http://<ip>v1/resources/workspace1/project1
{
    "@context": [
        "https://bluebrain.github.io/nexus/contexts/search.json",
        "https://bluebrain.github.io/nexus/contexts/resource.json"
    ],
    "_total": 0,
    "_results": []
}`

Here are the attached images that might help explain the bug
Images
https://github.com/mdamanuddin/imagesbug

**Comment by bogdanromanx** [comment]
@mdamanuddin there's a slight delay between the first resource creation and when it gets indexed into ElasticSearch as the event log is replayed in time buckets since the configured initial time (currently 01/01/2018). The interface should show the current status of the index (at the top next to the project label).
Could you please allow a couple of seconds (10-20 depending on your machine spec) to confirm that this is the case?

**Comment by mdamanuddin** [comment]
Didn't work. Also, got this output after I created the project, and went clicked on sparkql.

`SPARQL-QUERY: queryStr=# Directly edit this query SELECT ?s ?p ?o WHERE {?s ?p ?o} LIMIT 20 java.util.concurrent.ExecutionException: java.lang.RuntimeException: com.bigdata.rdf.sail.webapp.DatasetNotFoundException: namespace=kg_e28b25e1-d877-4b1a-8d24-1011a395de58_d88b71d2-b8a4-4744-bf22-2d99ef5bd26b_1 at java.util.concurrent.FutureTask.report(FutureTask.java:122) at java.util.concurrent.FutureTask.get(FutureTask.java:192) at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:294) at com.bigdata.rdf.sail.webapp.QueryServlet.doSparqlQuery(QueryServlet.java:678) at com.bigdata.rdf.sail.webapp.QueryServlet.doPost(QueryServlet.java:275) at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:269) at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancyServlet.java:195) at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220) at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at org.eclipse.jetty.server.Server.handle(Server.java:503) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.RuntimeException: com.bigdata.rdf.sail.webapp.DatasetNotFoundException: namespace=kg_e28b25e1-d877-4b1a-8d24-1011a395de58_d88b71d2-b8a4-4744-bf22-2d99ef5bd26b_1 at com.bigdata.rdf.sail.BigdataSail.getReadOnlyConnection(BigdataSail.java:1507) at com.bigdata.rdf.sail.BigdataSailRepository.getReadOnlyConnection(BigdataSailRepository.java:139) at com.bigdata.rdf.task.AbstractApiTask.getQueryConnection(AbstractApiTask.java:247) at com.bigdata.rdf.task.AbstractApiTask.getQueryConnection(AbstractApiTask.java:221) at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:746) at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:695) at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ... 1 more Caused by: com.bigdata.rdf.sail.webapp.DatasetNotFoundException: namespace=kg_e28b25e1-d877-4b1a-8d24-1011a395de58_d88b71d2-b8a4-4744-bf22-2d99ef5bd26b_1 at com.bigdata.rdf.sail.BigdataSail$BigdataSailConnection.<init>(BigdataSail.java:2072) at com.bigdata.rdf.sail.BigdataSail$BigdataSailReadOnlyConnection.<init>(BigdataSail.java:5236) at com.bigdata.rdf.sail.BigdataSail._getReadOnlyConnection(BigdataSail.java:1540) at com.bigdata.rdf.sail.BigdataSail.getReadOnlyConnection(BigdataSail.java:1503) ... 10 more`

**Comment by mdamanuddin** [comment]
The error is unresolved, Still no resources that can be fetched by the frontend or the api. Also, docker-compose throws the following error.  

`router_1         | 10.6.0.8 - - [26/May/2020:16:25:22 +0000] "GET /v1/views/someorg/test/nxv:defaultSparqlIndex/statistics HTTP/1.1" 500 171 "http://10.3.9.242/someorg/test/nxv:defaultSparqlIndex/sparql" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Mobile Safari/537.36" "-"
kg_1             | 2020-05-26 16:25:31 WARN  akka.cluster.sharding.ShardRegion - project-view-coordinator: Retry request for shards [11] homes from coordinator. [12] total buffered messages.
kg_1             | 2020-05-26 16:25:31 WARN  akka.cluster.sharding.ShardRegion - project-attributes-coordinator: Retry request for shards [11] homes from coordinator. [4] total buffered messages.
kg_1             | 2020-05-26 16:25:31 ERROR I.e.b.n.s.c.t.ServiceDescription] - Unexpected response for Storage call. Request: 'HttpMethod(GET) http://localhost:8084'
kg_1             | akka.stream.StreamTcpException: Tcp command [Connect(localhost:8084,None,List(),Some(10 seconds),true)] failed because of java.net.ConnectException: Connection refused
kg_1             | Caused by: java.net.ConnectException: Connection refused
kg_1             | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
kg_1             | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
kg_1             | 	at akka.io.TcpOutgoingConnection$$anonfun$connecting$1.$anonfun$applyOrElse$3(TcpOutgoingConnection.scala:104)
kg_1             | 	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:51)
kg_1             | 	at akka.io.TcpOutgoingConnection$$anonfun$connecting$1.applyOrElse(TcpOutgoingConnection.scala:104)
kg_1             | 	at akka.actor.Actor.aroundReceive(Actor.scala:533)
kg_1             | 	at akka.actor.Actor.aroundReceive$(Actor.scala:531)
kg_1             | 	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:32)
kg_1             | 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
kg_1             | 	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
kg_1             | 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
kg_1             | 	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
kg_1             | 	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
kg_1             | 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
kg_1             | 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
kg_1             | 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
kg_1             | 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
kg_1             | 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
kg_1             | 2020-05-26 16:25:31 WARN  [%PARSER_ERROR[traceToken]] c.e.b.nexus.kg.routes.AppInfoRoutes - Could not fetch service description for service 'remoteStorage'
kg_1             | ch.epfl.bluebrain.nexus.storage.client.StorageClientError$UnknownError: The request did not complete successfully.
kg_1             | 2020-05-26 16:25:41 WARN  akka.cluster.sharding.ShardRegion - project-attributes-coordinator: Retry request for shards [11] homes from coordinator. [4] total buffered messages.
kg_1             | 2020-05-26 16:25:41 WARN  akka.cluster.sharding.ShardRegion - project-view-coordinator: Retry request for shards [11] homes from coordinator. [12] total buffered messages`

**Comment by mdamanuddin** [comment]
Also, these messages keep coming from kg_1 image in docker.
` - - [26/May/2020:16:31:50 +0000] "GET /version HTTP/1.1" 504 569 "http://10.3.9.242/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" "-"
kg_1             | 2020-05-26 16:31:50 INFO  akka.actor.ActorSystemImpl - Request timeout encountered for request [GET /version Strict(0 bytes)]
kg_1             | 2020-05-26 16:31:54 WARN  akka.cluster.sharding.ShardRegion - project-view-coordinator: Retry request for shards [11] homes from coordinator. [17] total buffered messages.
kg_1             | 2020-05-26 16:31:54 WARN  akka.cluster.sharding.ShardRegion - project-attributes-coordinator: Retry request for shards [11] homes from coordinator. [4] total buffered messages.
kg_1             | 2020-05-26 16:32:04 WARN  akka.cluster.sharding.ShardRegion - project-attributes-coordinator: Retry request for shards [11] homes from coordinator. [4] total buffered messages.
kg_1             | 2020-05-26 16:32:04 WARN  akka.cluster.sharding.ShardRegion - project-view-coordinator: Retry request for shards [11] homes from coordinator. [17] total buffered messages.
kg_1             | 2020-05-26 16:32:14 WARN  akka.cluster.sharding.ShardRegion - project-view-coordinator: Retry request for shards [11] homes from coordinator. [17] total buffered messages.
kg_1             | 2020-05-26 16:32:14 WARN  akka.cluster.sharding.ShardRegion - project-attributes-coordinator: Retry request for shards [11] homes from coordinator. [4] total buffered messages.
kg_1             | 2020-05-26 16:32:24 WARN  akka.cluster.sharding.ShardRegion - project-view-coordinator: Retry request for shards [11] homes from coordinator. [17] total buffered messages.
kg_1             | 2020-05-26 16:32:24 WARN  akka.cluster.sharding.ShardRegion - project-attributes-coordinator: Retry request for shards [11] homes from coordinator. [4] total buffered messages.
kg_1             | 2020-05-26 16:32:34 WARN  akka.cluster.sharding.ShardRegion - project-attributes-coordinator: Retry request for shards [11] homes from coordinator. [4] total buffered messages.
kg_1             | 2020-05-26 16:32:34 WARN  akka.cluster.sharding.ShardRegion - project-view-coordinator: Retry request for shards [11] homes from coordinator. [17] total buffered messages.
kg_1             | 2020-05-26 16:32:44 WARN  akka.cluster.sharding.ShardRegion - project-attributes-coordinator: Retry request for shards [11] homes from coordinator. [4] total buffered messages.
kg_1             | 2020-05-26 16:32:44 WARN  akka.cluster.sharding.ShardRegion - project-view-coordinator: Retry request for shards [11] homes from coordinator. [17] total buffered messages.
kg_1             | 2020-05-26 16:32:54 WARN  akka.cluster.sharding.ShardRegion - project-attributes-coordinator: Retry request for shards [11] homes from coordinator. [4] total buffered messages.
kg_1             | 2020-05-26 16:32:54 WARN  akka.cluster.sharding.ShardRegion - project-view-coordinator: Retry request for shards [11] homes from coordinator. [17] total buffered messages.
kg_1             | 2020-05-26 16:33:04 WARN  akka.cluster.sharding.ShardRegion - project-attributes-coordinator: Retry request for shards [11] homes from coordinator. [4] total buffered messages.
kg_1             | 2020-05-26 16:33:04 WARN  akka.cluster.sharding.ShardRegion - project-view-coordinator: Retry request for shards [11] homes from coordinator. [17] total buffered messages.
kg_1             | 2020-05-26 16:33:14 WARN  akka.cluster.sharding.ShardRegion - project-attributes-coordinator: Retry request for shards [11] homes from coordinator. [4] total buffered messages.
kg_1             | 2020-05-26 16:33:14 WARN  akka.cluster.sharding.ShardRegion - project-view-coordinator: Retry request for shards [11] homes from coordinator. [17] total buffered messages.
kg_1             | 2020-05-26 16:33:25 WARN  akka.cluster.sharding.ShardRegion - project-attributes-coordinator: Retry request for shards [11] homes from coordinator. [4] total buffered messages.
kg_1             | 2020-05-26 16:33:25 WARN  akka.cluster.sharding.ShardRegion - project-view-coordinator: Retry request for shards [11] homes from coordinator. [17] total buffered messages.
`

``

**Comment by mdamanuddin** [comment]
This error is popping every few minutes from the docker-compose output
`| 2020-05-26 16:38:37 WARN  akka.cluster.sharding.ShardRegion - project-attributes-coordinator: Retry request for shards [11] homes from coordinator. [4] total buffered messages.
kg_1             | 2020-05-26 16:38:45 ERROR I.e.b.n.s.c.t.ServiceDescription] - Unexpected response for Storage call. Request: 'HttpMethod(GET) http://localhost:8084'
kg_1             | akka.stream.StreamTcpException: Tcp command [Connect(localhost:8084,None,List(),Some(10 seconds),true)] failed because of java.net.ConnectException: Connection refused
kg_1             | Caused by: java.net.ConnectException: Connection refused
kg_1             | 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
kg_1             | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
kg_1             | 	at akka.io.TcpOutgoingConnection$$anonfun$connecting$1.$anonfun$applyOrElse$3(TcpOutgoingConnection.scala:104)
kg_1             | 	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:51)
kg_1             | 	at akka.io.TcpOutgoingConnection$$anonfun$connecting$1.applyOrElse(TcpOutgoingConnection.scala:104)
kg_1             | 	at akka.actor.Actor.aroundReceive(Actor.scala:533)
kg_1             | 	at akka.actor.Actor.aroundReceive$(Actor.scala:531)
kg_1             | 	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:32)
kg_1             | 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
kg_1             | 	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
kg_1             | 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
kg_1             | 	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
kg_1             | 	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
kg_1             | 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
kg_1             | 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
kg_1             | 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
kg_1             | 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
kg_1             | 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
kg_1             | 2020-05-26 16:38:45 WARN  [%PARSER_ERROR[traceToken]] c.e.b.nexus.kg.routes.AppInfoRoutes - Could not fetch service description for service 'remoteStorage'
kg_1             | ch.epfl.bluebrain.nexus.storage.client.StorageClientError$UnknownError: The request did not complete successfully`

**Comment by wwajerowicz** [comment]
@mdamanuddin I see some error in the stack trace you provide regarded to [storages](https://bluebrainnexus.io//docs/api/current/kg/kg-storages-api.html). Did you create a Storage instance in your deployment?

**Comment by mdamanuddin** [comment]
No, how do we create that? I see no documentation on setting that up, or maybe i missed it.
Thanks for all the help @wwajerowicz @bogdanromanx

**Comment by adulbrich** [comment]
@am4nu Documentation for storages is available here https://bluebrainnexus.io/docs/delta/api/storages-api.html
Hope this helps. Don't hesitate to open a new discussion.
