### ISSUE TITLE
BBP studio Morphology plugin: adapt the default zoom level so that the whole morphology is visible

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1303]
jira (protected) https://bbpteam.epfl.ch/project/issues/browse/SSCXDIS-245?src=confmacro

**Comment by kenjinp** [comment]
![Screenshot from 2020-07-22 14-57-37](https://user-images.githubusercontent.com/5485824/88188119-b4fd7b00-cc37-11ea-887b-d2fbe0cdc371.png)
![Screenshot from 2020-07-22 16-15-32](https://user-images.githubusercontent.com/5485824/88188122-b5961180-cc37-11ea-9278-6761a0061591.png)

Testable using this example resource shown in the images (protected)
https://bbp.epfl.ch/neurosciencegraph/data/neuronmorphologies/6985d596-7e01-4a80-bff9-8cff9068ac81

I've also removed the zoom level input as it's no longer necessary.

**Comment by kenjinp** [comment]
from review:
- soma color should be black, not randomly generated
- camera distance offset should be less extreme

**Comment by kenjinp** [comment]
more feedback!

-     Please display somehow the X, Y and Z axis so that we have an idea of the orientation of the cell.
-     The camera should be pointing to the soma and the axis of rotation should be centered at the soma. This is very important - this is not usable as it is right now.
-     X, Y and Z axis can be use to get an idea of the scale of the cell. Currently we don't have any idea if the cell is big or small as there is no scale anywhere.
-     Can you add a button to make it fullscreen ?

**Comment by adulbrich** [comment]
And even more feedback (from SK):
In [this](https://staging.nexus.ocp.bbp.epfl.ch/bbp/nmc/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Freconstructedcell%2Fa9f73e3e-33c9-4f45-94a7-5d4f925afc57) entity:
- Soma is not visible
- The legend says the soma should be black but in the “Show as Geometry” view it looks like the dendrite are black. If I switch to “Show as Lines” the dendrite are red rather than black.
- The loading of the Geometry view is rather slow (3-4secs on my machine), a progress indicator could help. In comparison the Lines view is fast.
- The whole page freezes when Geometry view loads.

**Comment by kenjinp** [comment]
Feedback capture in new issues so we can close this one

#1468
#1467 
#1466 
#1465
