### ISSUE TITLE
Use-cases Pages

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1346]
part of https://github.com/BlueBrain/nexus/issues/989

1sp

**Comment by Stafeeva** [comment]
![screencapture-localhost-8000-epfl-bbp-html-2020-07-28-14_21_10](https://user-images.githubusercontent.com/23080476/88668341-c684ce00-d0e2-11ea-812e-903ef49e06f5.png)

![screencapture-localhost-8000-epfl-bbp-html-2020-07-28-14_20_47](https://user-images.githubusercontent.com/23080476/88668359-cb498200-d0e2-11ea-9ffc-312ea03a6c2d.png)

**Comment by adulbrich** [comment]
Looking good! 

Couple points:
- Could we remove the "Features" from header everywhere?
- The header should be "Blue Brain Nexus" instead of just "NEXUS" (cfr. communication's team guidelines)
- Mobile view: the text after the h1 title could become quite long. Should be limit to e.g. 250 characters and allow user to expand (read more) if the text is longer? So that we have buttons displayed immediately?

**Comment by kenjinp** [comment]
We've decided to remove these pages from the product page until a future version
