### ISSUE TITLE
Preview all types of images with image plugin, allow download of images in download plugin

### ISSUE THREAD

**Issue by dhaneshnm** [BlueBrain/nexus#1420]
This is a feature request from genrich.ivaska@epfl.ch.
Some of the files in the download section are images (png/jpg etc). User will benefit if they can preview these images in the plugin.

Note : We also have a image viewer plugin where files can be downloaded. May be we can configure that to show all images. Currently it appears only if the images are part of ephys distribution.

See https://github.com/BlueBrain/nexus/issues/1696 and https://github.com/BlueBrain/nexus/issues/1352

**Comment by adulbrich** [comment]
I would recommend to show the image plugin anytime there is a detected image extension. 👍

**Comment by dhaneshnm** [comment]
Blocked due to : https://github.com/BlueBrain/nexus/issues/1558

**Comment by chr-pok** [comment]
Hi! I recently learned about the image viewer plugin which is a very useful feature! I use it for visualization of simulation campaign results, which consist of results images for different parameter values in a certain range (reflected in their filenames). I use bbp-workflow for results generation and registration in Nexus, resulting in a PlotCollection entry.

I noticed that the order of images in the viewer seems to be random (at least I could not see any pattern). Moreover, each time I register a new revision of results with identical settings, images, filenames, etc. the order seems to be different. This makes the interpretation of results a bit difficult.

So I was wondering how the order of images is determined, and if there is any way to control the order of images when registering the results in Nexus? It would be very helpful to have images sorted, for example alphabetically based on their filenames. Beyond that, a well-defined row/column organization would be even more useful, since our simulation campaigns often consist of 2D sweeps of two independent parameters.

**Comment by adulbrich** [comment]
@chr-pok the image plugin is under review, we'll make a multiple image viewer available hopefully by end of February 2020. We'll include a search filed (based on filename) and sorting based on image metadata.

**Comment by annakristinkaufmann** [comment]
Hi @adulbrich @kenjinp @dhaneshnm :
I would also be interested in the multiple image viewer plugin :) Thanks for looking into that!
Related to that, uploading an image file such as PNG currently allows one to view the image directly on the file resource, however there seems to be a bug with displaying the image multiple times next to each other. For an example, see e.g. this file resource: https://bbp.epfl.ch/nexus/web/bbp/lnmce/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2F781c17ba-b818-4997-97c9-e92e3b3cf743

**Comment by adulbrich** [comment]
We are working on https://github.com/BlueBrain/nexus/issues/1696 this sprint. Hopefully, it will solve part of the problems listed here!

**Comment by adulbrich** [comment]
This is done. The image collection viewer is deployed and maps to resources that have an `image` property or a `distribution` property with a File of type image. It does not work on Traces (because Traces have their own dedicated plugin).

You can check all plugin mappings [here](https://bbp.epfl.ch/nexus/plugins/manifest.json).

```json
"mapping": [
      {
        "image": {}
      },
      {
        "distribution": {
          "@type": "File",
          "_mediaType": [
            "image/*"
          ]
        }
      }
    ],
    "exclude": {
      "@type": [
        "Trace"
      ]
    },
```
