### ISSUE TITLE
SWC parser fails to parse certain morphologies

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#1561]
The problem happens when some node doesn't have a parent during the `TreeNodeCollection` init process

> Morphology parsing error: Cannot read property '_addChild' of undefined

```typescript
 /**
   * Parses a SWC string. This SWC string is simply the text content of an SWC file.
   * This method does not return any reult (use one of the getters for that)
   * @param {String} swcStr - the string that comes from the SWC file
   */
  parse(swcStr) {
    this._morphology = null
    this._rawMorphology = null
    const rawPoints = SwcParser.extractPoints(swcStr)
// the problem happens here
    const treeNodeCollection = new TreeNodeCollection(rawPoints)
    this._morphology = treeNodeCollection.getMorphology()
    this._rawMorphology = treeNodeCollection.getRawMorphology()
  }

```

**Comment by jonathanlurie** [comment]
Hey @kenjinp ,
I just fixed this in the original repo [here](https://github.com/jonathanlurie/swcmorphologyparser). In case you are not using this repo but a fork/copy of the code, here is what has changed:
- adding `setParentId()` [here](https://github.com/jonathanlurie/swcmorphologyparser/blob/master/src/TreeNode.js#L94)
- adding `getParentId()` [here](https://github.com/jonathanlurie/swcmorphologyparser/blob/master/src/TreeNode.js#L104)
- modified `_initCollection()` [here](https://github.com/jonathanlurie/swcmorphologyparser/blob/master/src/TreeNodeCollection.js#L56)

The reason of the error was because the parser expects the node of id `n` to be listed before any point has the node `n` as a parent node. In all the SWC files I've seen earlier, this is what happens so for performance reasons I've implemented that in a single loop, where all the parent nodes are already existing when their children claim them as parents. In the case of this new batch of morphs, some child nodes are defined earlier in than their parent in the list.

The fix consists in having two loops instead of one (one loop happens after the other, not in a nested way). The first loop instantiates all the node objects BUT, instead of directly associating each node with their parent node instance, it associates them with only their parent id (a number). In the second loop, each node object looks up for its parent based on the parent id they have as an attribute. Ultimately, it's a tad slower, but I don't think one can perceive it, and to be honest, I remember saying to myself 2 years ago "I hope the nodes are always declared in a parent-first fashion, otherwise this will break". Here we are :D
