### ISSUE TITLE
Total event count collection seem to restart in case of a Cassandra timeout

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#1689]
In cases where there's a lot of pressure on the primary store (that results in timeouts), the event count collection is restarted from 0. The causes incorrect results in the `/statistics` sub-resource of views.
The total event count is executed for each project concurrently, adding unnecessary pressure on the primary store.
Whenever the system is restarted the event count collection is recomputed.

Proposed changes:

1. have a single event log replay that computes the event count for each project
2. store the counts such that they survive restarts

**Comment by umbreak** [comment]
1 can be done easily.
2 not that much.

Since for 1.5.x we have already discussed a solution for this type of issues (having a centralized polling rate) I would not invest too much time on having a solution for 1.4.x

Where does the timeout happen? We could have retry mechanism in place to avoid this for now.

**Comment by bogdanromanx** [comment]
The timeout error happens in the Akka Source of the event log, collapsing the entire stream. What if we only consider 2? would that be simpler?

**Comment by umbreak** [comment]
It seems to me out of scope since it is something we are not currently doing. We would have to add several things which can take a while. Better to wait for 1.5.x

**Comment by umbreak** [comment]
I'll try with 2)

**Comment by umbreak** [comment]
I was wrong, storing the offset of a Stream was easy thanks to `ProgressFlow` implementation.

Having all the projects statistics be computed out of a single stream is more complicated, since we would have to add the logic to compute the statistics for each project separately.

In any case, the reported bug is fixed: when a view restarts (intentionally or because of a crash) or the full service restarts, the totalCount (coming from the project event count) will start from where it left of.
