### ISSUE TITLE
Ensure cache consistency when the service boots up for realm, resolvers and storages

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#1806]
Realms have an unicity constraint on the openIdConfig uri that cannot be enforced during the service bootstrap.
Resolvers have an unicity constraint on the priority that cannot be enforced during the service bootstrap.

Replay the current events by tag for these resources when the service starts to populate the cache and bind the routes only after this operation is complete.

**Comment by wwajerowicz** [comment]
The easiest way we can achieve this is by setting these properties in config:
```
akka.cluster.distributed-data.durable {
        keys = ["*"]
        lmdb.dir = "/tmp/delta-cache" #we need to decide on this path
 }
```
However, these requires changes to `ResourceF`, because Akka fails to deserialize it due to properties which are functions:

```scala
id: BaseUri => Iri,
accessUrl: BaseUri => Uri,
incoming: BaseUri => Option[Uri] = _ => None,
outgoing: BaseUri => Option[Uri] = _ => None
```
A solution for this has been discussed here https://github.com/BlueBrain/nexus/pull/1835#pullrequestreview-538617211

To verify that it works, start the service, create some resources (e.g. via integration test), restart the service and check that the cash has been successfully read from disk.
