### ISSUE TITLE
Listing resolvers returns more properties

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#1902]
Compared to v1.4, listing resolvers now also return priority, projects and other user-defined fields

**Comment by umbreak** [comment]
Is this an issue? The addition of fields is not an API breaking change, just the removal of them. If it is just a comment, please add it to the list in https://github.com/BlueBrain/nexus/issues/1828

**Comment by imsdu** [comment]
We can talk about it but we removed these properties from the responses from the create/update/deprecate operations so it would make sense to remove them also here

**Comment by umbreak** [comment]
listing is not a write operation, but a read operation. When you fetch a resolver you get those fields, right?

**Comment by imsdu** [comment]
It would be more consistent with the other listings yes

**Comment by umbreak** [comment]
Yes. Since we are using the actual Distributed Data cache to provide with listings in most of the resources, we should be getting the same sort of response (not only metadata fields, but also other fields) for those listings as well.

The exception here are resources for where listings come from Elasticseaarch, since we have a common ES mapping. For those we will keep returning only metadata fields.
