### ISSUE TITLE
Investigate v1.4-v1.5 migration solutions

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#1923]
Build a PoC that demonstrates a viable migration solution such that the changes in how resources are stored (precomputed expanded form) can be adapted from the v1.4 storage format: i.e.: demonstrate the migration of v1.4 event format to v1.5.

Attempt a migration of data from an existing v1.4 environment to identify possible issues.

If the migration process is expected to last a long time evaluate the possibility of continuing the run v1.4 while the migration is being executed.

Evaluate the possibility to pause / stop / resume / restart the migration process.

The PoC should also demonstrate error logging in cases where the migration code cannot handle the previous format or in cases where a resource cannot be converted to an expanded json-ld format due to updates to resolvers post creation. Should the log be persistent (i.e. DB)? or text files are sufficient?

Can the migration logic coexist with the v1.5 service package (image)?

**Comment by imsdu** [comment]
**Setup**
- Make sure at the free disk space for Cassandra is twice as much as the occupied space
- Create a second keyspace
- Start a second delta application with a migration flag starting a migration module

**Migration module**
- This migration module will start a CassandraJournal pointing on the previous keyspace and start an eventByTag query on every event
- Substitute org/proj uuids for org/proj labels when needed
- Every event will be submitted to the right module according to its type
- Add a temporary operation in Projects/Organization to create one with a defined UUID

**Error handling**
- In case of error, we write in a cassandra table (we can then export this table as csv if needed)
- As we use the eventByTag query, we can start from a defined offset

**Verifying data**
- API endpoints are available so we can compare responses from both 1.4 and 1.5
- Checking errors in errors table
- Checking number of events in original keyspace equals number of events in the new one + number of errors
- Add a job that finds  events missing from the migrated keyspace

**Comment by umbreak** [comment]
There is no mention to Json-LD compaction and expansion. I think that, plus the compute of the fat-schema are gonna be the most difficult points.

- In order to retrieve the expanded and compacted form of an event, you will need to call the 1.4.x API `/v1/resources/{org}/{proj}/_/{id}?format=compacted|expanded`. Note that this can yield errors for unexpected context changes

- In order to compute the fat-schema you will need to follow and fetch all the `owl:imports` links and create a expanded jsonld with all those links as entries.

- Another item which will be tricky to migrate is the field `schemaProject` in `ResourceEvent` since we didn't store this information before (also the revision of the schema). You'll have to figure out where the schema came from checking if it exists in the same project and then checking if it exist somewhere else using the `v1/resolvers/{org}/{proj}/_/{id}` endpoint in 1.4.x

**Comment by imsdu** [comment]
All these points should be taken care of by passing the source to the Resources/Schemas module no ?

For example:
1) The event by tag query fetched a Resource creation/update event
2) We pass the id, the source, the schema to the Resources operation
3) The compacted/expanded form and the schemaProject will be computed at this moment.

Same idea with the schema.

**Comment by umbreak** [comment]
I understand that your approach is:
1. Read the whole eventlog using eventsByTag from 1.4.x
2. For each event delegate to the actual implementation passing the event id, source, subject and, schema. E.g.: Resources.create, Schemas.create, Resolvers.deprecate

This will probably work. If you want to do it this way, you'll need to call `eventsByTag("event")` and then depending on the `types` on each event, call `Resources.*`, `Schemas.*`, etc. This must be done sequentially. Otherwise a crossproject needed to resolve a context might not be present when required.

You will have to substitute not only `UUID`s, but also `Instant`.

**Comment by umbreak** [comment]
Probably you want to do it differently for Files, since this approach wouldn't really work. In that case you'll have to take the original Event from 1.4.x and adapt it manually to 1.5.x (it should be straight forward in this case).

**Comment by umbreak** [comment]
And for storages, concretely for `RemoteDiskStorage` you might encounter cases where GPFS permissions changed. and we don't have access anymore to a certain folder that we did have access in the past. However I don't think in practice that's the case, so it will be enough logging it, as suggested

**Comment by imsdu** [comment]
For akka persistence, we can have two different actor systems in one jvm so the idea is to create a second one especially for the migration module.
For the different events there may be some adaptations yes, for Files we can add another operation that just import the event without interacting with the storages
