### ISSUE TITLE
Admin Plugin: Allow navigation of resources by versioned identifiers

### ISSUE THREAD

**Issue by annakristinkaufmann** [BlueBrain/nexus#2082]
Currently, Nexus Fusion only allows navigation (e.g. through the **links**) of non-versioned identifiers (`@id`). It would be nice to have the option to also navigate linked resources when they are linked through a versioned identifier (`@id`)

**Comment by samuel-kerrien** [comment]
Had a discussion with @annakristinkaufmann this morning to clarify that issue.

Setup:  
 - MacOS: 11.6 
 - Browser: Chrome 95.0.4638.69; 
 - Fusion in Staging env; version: 1.7.0-M2;

Here are some steps to reproduce:

1. Open Fusion, go to an entity in the Admin Plugin

2. Create a first entity (A)
`
{
  "@type": [
    "https://schema.org/Person"
  ],
  "https://schema.org/name": "Harry"
}
`

3. Create a second entity (B)
`
{
  "@type": [
    "https://schema.org/Person"
  ],
  "https://schema.org/name": "sally"
}
`

4. Create a modification of B, to create a second revision (here just updating the name):
`
{
  "@type": [
    "https://schema.org/Person"
  ],
  "https://schema.org/name": "Sally"
}
`

5. Update entity A and add a link to entity B (no revision at this stage, so pointing to the LATEST revision):
`
{
  "@type": [
    "https://schema.org/Person"
  ],
  "https://schema.org/knows": {
    "@id": "<ID OF ENTITY B>"
  },
  "https://schema.org/name": "Harry"
}
`

6. Now, still in the Admin Plugin, go to the Links tab and see the following:
![Screenshot 2021-11-25 at 14.35.43.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/74f14432-7d28-415a-a9e2-a9abf2a726c2)
If you click on the outgoing link, it refreshes the Resource Panel with that other Person (B). So far so good, this is the expected behaviour.

7. Now let's edit again entity A and change the link to entity B to be pointing to a specific revision (e.g. revision 1) by simply adding the query parameter 'rev=1':
`
{
  "@type": [
    "https://schema.org/Person"
  ],
  "https://schema.org/knows": {
    "@id": "<ID OF ENTITY B>?rev=1"
  },
  "https://schema.org/name": "Harry"
}
`

8. Now, let's go back to the Links tab and click on the outgoing link, it opens a blank page.
![Screenshot 2021-11-25 at 14.40.33.png](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/de4e787d-7aab-4c21-a6ce-31a2c5a5b833)
other observation: the outgoing link isn't formatted the same, it now shows the full URL rather than the UUID.
