### ISSUE TITLE
ACLs applied on project creation are wrong

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2119]
This can be reproduced by the test on `ViewsSpec` (integration tests):
1. Set permissions orgs/create  to /org1
2. Create the org1
3. Attempt to create org1/proj1  gives back a forbidden

But It works If I change the test to do:
1. Set permissions orgs/create  to /
2. Create the org1
3. Creates org1/proj1

**Comment by wwajerowicz** [comment]
The ACLs applied on project creation are correct. In the case in the issue description,   if you set `orgs/create` on `/org1`, before creating the organization, the owner permissions for `org1` will not be applied, because we don't override existing permissions. The result is that when you create `org1` you still only have `orgs/create`  permissions on the org, but none of the other permissions, especially `projects/create`.  Therefore it's not possible to create the project.

**Comment by adulbrich** [comment]
expected behavior

**Comment by adulbrich** [comment]
expected behavior
