### ISSUE TITLE
Automate Data Ingestion

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#214]
_From @kenjinp on October 18, 2018 13:59_

Specifically for morphology release, at least, to start.

Can be enough to create a job that handles this, but ideally would read the stream of events that Nexus produces. 

connects #212 

_Copied from original issue: BlueBrain/nexus-search-webapp#111_

**Comment by kenjinp** [comment]
After some trials using making a kafka stream consumer to listen to events, I think that's not the way to go. This is because we don't have a nexus service account for the consumer, so it cannot (easily) read the entities from nexus once a new event has been emitted. 

So we could
- Make a user interface to re-sync search, using the user's token
- Re-assemble the graph from the JSON payloads from kafka's history. 

I think the best strat here is making a "Sync Search" interface.

**Comment by bogdanromanx** [comment]
For v1 we can create a service account to support this workflow. I would very much recommend using an incremental approach to migrate data over a user triggered one.

**Comment by bogdanromanx** [comment]
Sounds good to me! ;)

**Comment by kenjinp** [comment]
This is currently only implemented for Morphology Releases, with other data types coming soon!
