### ISSUE TITLE
Opening File resources results in JSON payload error

### ISSUE THREAD

**Issue by nicwells** [BlueBrain/nexus#2569]
Uploading a file via the UI result in a "Failed to load JSON payload - An unknown error occurred" error.

![resource-creation-bug](https://user-images.githubusercontent.com/11296166/123602017-9ebd4f00-d7f8-11eb-8ab5-57620343058a.gif)

Acceptance Criteria:
- The user can see the file JSON payload and all the other tabs in the admin plugin should work as for any resource
- The file payload cannot be edited: either the editing is disabled, or we show a proper error message on save, saying that File resources cannot be edited.

**Comment by nicwells** [comment]
@dhaneshnm @adulbrich is this a known bug?

**Comment by adulbrich** [comment]
@nicwells this is related to the ticket that @smitfire completed earlier this sprint https://github.com/BlueBrain/nexus/issues/1407

**Comment by adulbrich** [comment]
@bogdanromanx @dhaneshnm I understand we don't get back the payload for Files. Is that something we can fix? Or should we just exclude files from the indexing?

**Comment by bogdanromanx** [comment]
What API call is performed? What value is sent in the `Accept` header? To get the json ld representation, the value of the header should be `application/ld+json`, otherwise the binary will be returned instead.

**Comment by bogdanromanx** [comment]
The error appears because Fusion is making a call to get the resource source, which for files Delta replies with a 404. We need to evaluate if pre v1.5 one could get the file source, and if that is the case, we should implement it. Otherwise, Fusion can be adjusted to avoid calling `/source` for files.

**Comment by nicwells** [comment]
Have confirmed for Fusion at least that no changes to its behaviour since pre v1.5, i.e. Fusion would have attempted call to /source endpoint to show JSON payload for all resource types. Earliest commit checked from 28-Oct-2019: https://github.com/BlueBrain/nexus-web/commit/2adb840033f69d076b87ebf0b66c62b36e91123a

**Comment by umbreak** [comment]
Files `/source` was returning an empty Json, since Files by definition do not have a payload (they do have an attachment, but not a payload). That's why it was removed on v1.5.

In case of files you should not ask for the source. However, you can fetch the file metadata by using `Accept: application/ld+json`.

**Comment by adulbrich** [comment]
Acceptance criteria passed, but the JSON code area still says "Directly edit this resource". Any way we can make it non-editable? That way we could also remove the blue infobox?

![image](https://user-images.githubusercontent.com/11705901/133201796-58888859-2d8a-4dd7-b5bf-3a2fddff48a7.png)
