### ISSUE TITLE
Listings sort parmeter only allows for metadata sorting

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#2596]
Organizations and Projects could also be sorted by other metadata fields (label, uuid, etc).

Requested by @Stafeeva

**Comment by adulbrich** [comment]
This needs to support an actual use case in Fusion. 
Right now it would help because the orgs and projects are difficult to browse in admin. Having them sorted alphabetically would be useful!

We should consider the best UI options first:

1. Instead of browsing orgs then projs, we could show all the user's projects directly.
2. Keep the current orgs/projs browsing mechanism but improve the layout.

**Comment by umbreak** [comment]
Default sorting is by date of creation. But when there are many projects, it can become difficult to list them, indeed.

**Comment by adulbrich** [comment]
@umbreak looking at the docs, it seems you can give another field to sort on?

https://bluebrainnexus.io/docs/delta/api/projects-api.html#list

What would happen if I wrote?

```
GET /v1/projects?sort={label}
```

**Comment by umbreak** [comment]
From the docs:
> {sort}: String - orders the resulting projects based on its metadata fields. Optional parameter that can appear multiple times, further specifying the ordering criteria. Defaults to _createdAt, ordering projects by creation date.

The docs does not specify which are the allowed values for the `sort` query params. However I can tell you that for projects those are the allowed values:
- @id
- _rev
- _deprecated
- _createdAt
- _createdBy
- _updatedAt
- _updatedBy
- _constrainedBy
- _label
- _uuid
- _organizationLabel
- _organizationUuid
