### ISSUE TITLE
Only support valid Delta URIs (encoded)

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2603]
As reported by @MFSY:

Currently, I have to write (this might cause issues on clients) [as value to `distribution.contentURL` e.g.]:

> https://bbp.epfl.ch/nexus/v1/files/bbp/lnmce/https://bbp.epfl.ch/neurosciencegraph/data/fd68fe86-2424-42df-b4e4-d110d59bc805

Instead of (which is the best/preferred way of having HTTP URLs as paths in a URL):

> https://bbp.epfl.ch/nexus/v1/files/bbp/lnmce/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Ffd68fe86-2424-42df-b4e4-d110d59bc805

Affected (or to check) plugins: 

- data download
- metadata
- image
- pdf
- table
- ephys
- morpho

Acceptance Criteria:

- Handle `contentURL`s in the correct form, where the URL is encoded (e.g. `https://bbp.epfl.ch/nexus/v1/files/bbp/lnmce/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2Ffd68fe86-2424-42df-b4e4-d110d59bc805`)
- If the resource ID part of the `contentURL` is encoded, nothing should happen
- Display error message if the `contentURL` does not match the right format (e.g. `https://bbp.epfl.ch/nexus/v1/files/bbp/lnmce/https://bbp.epfl.ch/neurosciencegraph/data/fd68fe86-2424-42df-b4e4-d110d59bc805`)
- All plugins should handle it in the same way

Not in scope: 

- If the resource ID part of the `contentURL` is not encoded, we should encode it

**Comment by smitfire** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/2603?planning-poker) with ZenHub @adulbrich @bogdanromanx @dhaneshnm @imsdu @nicwells @samuel-kerrien

**Comment by adulbrich** [comment]
@MFSY are you comfortable with the acceptance criteria above?

**Comment by adulbrich** [comment]
@MFSY any feedback on this?

**Comment by adulbrich** [comment]
@dhaneshnm come up with list of examples to show impact for DKE (notify them once we have it)

**Comment by MFSY** [comment]
Hi,

Find below a description of this issue from my perspective. First of all, this is a bug to fix and not a feature request from my side.

Currently when display resources in some plugins, an already url encoded `_self` value is url encoded again leading to a double url encoding. The value of the resource `_self` property:

* is generated and controlled by Nexus Delta
* can be already url encoded (most of the time) or not

With this in mind, it would important to detect on the plugins side when it is already url encoded so that double url encoding is not happening.

Best.
