### ISSUE TITLE
Redesign support for remote storage locations

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2806]
Motivation:

- support for remote disk storages is fairly complex because it requires maintaining and running a separate service and secure communication (service account and token/acl checks)
- the rust module (permission fixer) uses deprecated functions that need to be replaced; it's also very specific to BlueBrain's usecases
- hash computation is inefficient because it relies on the allocated resources for the service instead of parallelising the computations on demand
- hashes are exchanged over the wire (not persisted immediately after computation) - cannot verify the integrity of data without having Delta running
- supporting features like replicas would be difficult in the current implementation because:
  - we would have to implement a storage service to storage service direct exchange and would imply deploying additional instances of the storage service
  - delta would still need to orchestrate the replica generation, increasing the complexity significantly (a minimum of three point coordination)

Acceptance criteria:

- evaluate the possibility of deprecating the RemoteDiskStorages and expose extensibility points to handle remote locations over local mount points (hash computation using slurm, relocation and application of permission changes over ssh)
- create a design proposal that handles the current capabilities of the system with respect to remote disk storages that doesn't rely on a separate service to mediate access to the remote location

**Comment by bogdanromanx** [comment]
The current design for handling storage of files in a remote location (the physical location of data is in a separate
datacenter) attempts to avoid the unnecessary transfer of data over the network, like for example, in the case of
linking an existing file, the hash of the file is computed within the same location with the data. But this introduces a
higher complexity and operational burden due to the additional storage integration service that needs to be maintained,
deployed and monitored.

The specific use cases that need to be supported are the following:

- upload a file (write file to the remote location)
- download a file (read file from the remote location)
- link an existing file or directory on the remote location; linking represents the action of materialising an existing
  file or directory on the remote location such that:
    - the hash of the file or directory is computed
    - a different ownership can be applied to the file or recursively to the directory
    - a different permission mask can be applied to the file or recursively to the directory
    - the file and directory is relocated (moved) such that it's within a specific subfolder of the storage bucket (
      e.g. `/buckets/bucket1/file.txt` would be relocated to `/buckets/bucket1/nexus/a/f/3/c/d/file.txt`) for
      appropriate grouping without collisions
    - the size, hash, content type and physical location is recorded in the event log
    - for large files that already exist on the remote location, there's no need to transfer the data between sites for
      computing the hash

An alternative extensible solution can be considered that addresses the use cases described above without a specific
need to run an instance of the storage service, as follows:

**1. Provide a new contract (sdk) for the operations required**

```
trait StoragePlugin {

  // returns the specific storage type supported by this plugin such that Delta knows where to delegate the fns
  def storageType: Iri
  
  // creates a new file on the target storage and synchronously returns the attributes of the newly uploaded file
  // meant to be invoked when a caller uploads a file through the system API
  def upload(storage: Storage, description: FileDescription, source: Stream[UIO, ByteVector]): IO[UploadFileRejection, FileAttributes]
  
  // retrieves a stream that can read the contents of a file
  // meant to be invoked when a caller downloads a file through the system API 
  def download(storage: Storage, attributes: FileAttributes): IO[DownloadFileRejection, Stream[UIO, ByteVector]]
  
  // materializes an existent file/directory and returns the FileAttributes
  // note: FileAttributes supports cases where the size or digest are not yet computed, because the operation can be expensive
  def materialize(storage: Storage, sourcePath: Uri.Path, description: FileDescription): IO[StorageFileRejection, FileAttributes]
  
  // returns the attributes of file or directory based on its path
  // it will be invoked in the situation where a file has been created/materialized, but the attributes could not be
  // computed synchronously; a separate stream will check all file revisions to see if they're missing the complete
  // attributes
  def fetchAttributes(storage: Storage, attributes: PartialFileAttributes): IO[FetchAttributeRejection, Option[CompleteFileAttributes]]

  // validates a Storage instance config against the plugin implementation for correctness
  def validate(config: Json): IO[InvalidStorageConfig, Unit]
  
  // validates and encrypts a Storage instance config against the plugin implementation for correctness
  def encrypt(config: Json): IO[InvalidStorageConfig, Secret[Json]]
  
  // decrypts the storage config
  def decrypt(config: Secret[Json]): IO[InvalidStorageConfig, Json]
}

sealed trait FileAttributes
case class PartialFileAttributes extends FileAttributes // does not contain size and digest
case class CompleteFileAttributes extends FileAttributes

```

**2. Move the entire file logic and the DiskStorage to the SDK/Service**

The capability of handling binary data through storages and files are essential, there's no need to have this logic
implemented as a plugin. The disk storage implementation would be bundled with the service.

Storage operations (create/update/deprecate/tag etc.) would be handled by the service component, by making use of the
registered plugins, indexed based on type. The storage config will be validated encrypted and decrypted by the plugin.

File operations will delegate to the storage plugin implementation (the DiskStorage will be implemented as a plugin).

The DI system will be used to register storage plugins:

```
make[DiskStoragePlugin].from { ... }
many[StoragePlugin].add[DiskStoragePlugin]
```

**3. Extract the S3 storage support to a separate plugin**

The S3 storage backend should be provided as a standalone plugin that implements the new contract. Since the S3 Storage
requires storing credentials, the Storage model needs to be updated to support configuration and secrets introduced by
plugins, like for example:

```
final case class Storage(
  id: Iri,
  storageType: Iri,
  project: ProjectRef,
  tags: Map[TagLabel, Long],
  algorithm: DigestAlgorithm,
  capacity: Option[Long],
  maxFileSize: Long,
  readPermission: Permission,
  writePermission: Permission,
  source: Secret[Json],
  config: Secret[Json]
)
```

**4. Write the size and digest of the file/folder on disk**

In order to check for data corruption without having the system running, when uploading or linking a file the computed
size and digest should be written on disk as a sibling file to the file or directory.

**5. Drop the current RemoteDiskStorage implementation**

This capability is only used at BlueBrain, a custom plugin should be implemented that supports BlueBrain's specific use
cases respecting the contract. In order to match the current functionality the following behaviour could be implemented:

- create a separate StoragePlugin instance
- mount the remote volume directly on the Delta node (e.g. through NFS)
- when uploading a file, the digest and size can be computed automatically and saved both on disk and in the event log
- when linking a file, a process can be started via SSH or Slurm to:
    - change the file/directory ownership recursively
    - apply the new permission mask to the file/directory recursively
    - compute the size/digest asynchronously and write them on disk
- the healing mechanism for fetching the CompleteFileAttributes will ensure that the async process is either running or
  has completed; if the process is not running and hasn't completed, it will be restarted
- a file or directory is read directly from the volume mount point

**6. Migration**

The current event log for storage events will no longer match the new model. Delta will have to expose the ability to
migrate current storage events to the new model, by starting the service in MIGRATION mode.

**7. Verify consistency of the current storages**

As with the new design for the ElasticSearchView Pipes, it is possible that a StoragePlugin could have been defined but
later removed from the system. A general mechanism for consistency checks for custom logic introduced by plugins should
be developed to reveal situations where existing data/configuration is no longer recognized. In the case of storages,
all storages where custom types are no longer supported by the discovered StoragePlugin instances should be listed.
