### ISSUE TITLE
Evaluate the use of a custom database schema

### ISSUE THREAD

**Issue by adulbrich** [BlueBrain/nexus#2911]
**Motivation**
Dropping Cassandra support enables the use of a custom schema with Postgres such that some queries can be directly executed against the database, without the need of a projection.

**Acceptance criteria**
1. Evaluate the akka-persistence-jdbc and akka-persistence-postgres plugins and propose an appropriate database schema that allows listing control resources per scope
2. Describe the required changes and approach (e.g. drop akka persistence?) in order to support the new schema
3. Describe all of the custom Cassandra support in Delta that can be removed
4. Describe any possible breaking changes for the API (e.g. Cassandra offset is UUID vs Postgres which is number)
5. Describe how migration would be performed (Cassandra -> Postgres and Postgres jdbc -> Postgres)

**Comment by imsdu** [comment]
1. Evaluate the akka-persistence-jdbc and akka-persistence-postgres plugins and propose an appropriate database schema that allows listing control resources per scope

* akka-persistence-jdbc
  * Does not allow to leverage postgresql specificities
  * Not easily extensible to our use-cases (ex. to use states for listing, we would need to implement some projections)

* akka-persistence-postgres 
  * Is still at version 0.5.0-m4
  * Allows to leverage postgresql specificities
  * Same interfaces as akka-persistence-jdbc, so not easily extensible

* Everything fits in one table, we have to rely on tags to discriminate event types
* It is not possible to stream directly states
* Serialization must be defined through configuration files

2. Describe the required changes and approach (e.g. drop akka persistence?) in order to support the new schema
If we drop `akka-persistence` to go for our own sourcing library, we could:
* Event metadata (at least part of it) would also be columns in the table 
  * No need for tags in the akka-persistence sense to stream back events
  * More composable (ex : get events from a given project from a certain type)
* Snapshots of the latest state
  * No need to scan and drop events for most projections
* Metadata would also be part of the snapshot columns
  * Drop the need of distributed caches for listings
  * We could also stream states directly and filter them like for events
* Have a better integration with fs2 / IO
* Easier to run queries for investigating problems 
* Easier to integrate from visualization/alerting tools

It would however needs a complete rewrite of the sourcing library.
Also using states for listings can also be problematic as they sometimes rely on some custom fields 
* For acls
* Finding project references in other projects before deletion
* Realms
* What if we need to add other custom metadata ?
* That also means, we have to add a lot of indices on the tables, so slowing down writes
* For most resources. we already have a listing in ES

If we keep `akka-persistence`:
* Less code to write
* We can still try to address problems about the current sourcing library
* We can add new tags as they don't require extra copies anymore (ex: tag events would have a tag in akka-p sense so as to make 
indexing faster for views filtering on a tag)
* We can enable snapshots
* Listings would still have to be done through projections, but we could use ES instead of a KV store (which has limits) ?
For projects / resolvers / views / acl, we could index more aggressively
* We keep the write model and the read model separated

3. Describe custom Cassandra support in Delta that can be removed
* Synchronous indexing
* Cooldown after deleting project
* Repair tags
* Project counts

4. Describe any possible breaking changes for the API (e.g. Cassandra offset is UUID vs Postgres which is number)
* SSE Offset (we could still retrieve an offset from a datetime)
* Remove streaming of all events ?

5. Describe how migration would be performed (Cassandra -> Postgres and Postgres jdbc -> Postgres)
Double run:
* The old version of Delta would still be accessible to users
* The new one would run in migration mode and stream down events to the new database schema
* When the new version has caught up, we perform additional checks to see if everything is ok
* We migrate projection progresses to go from UUID based offsets to sequence ones
* We turn off the old version, make the new one available to others

Interesting read:
https://softwaremill.com/implementing-event-sourcing-using-a-relational-database/
