### ISSUE TITLE
JIRA Integration PoC

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3039]
**Motivation**
To enable users to link 

**TODO**
[] Discuss with CS the configuration of JIRA so that Nexus can access the API endpoint

**Acceptance criteria**
1. Authentication into JIRA minimizing the need to log in again.
2. Configuration of the affinity between a Nexus project and a JIRA project in Project Settings.
3. Creation of a ticket with specific name, description, label ? (final list to be defined), in a configured project.
   a. Issue name can be tweaked by the scientist, default mentioned the name of the KG resource.
   b. there would be a way to discriminate Discussion issues (label? component? TBD)
   c. Link back from the issue to the Fusion view of that KG resource
4. Linking of an existing ticket (by ID or issue URL)
5. Listing of linked tickets to a specific KG resource
6. Unlinking of tickets
7. Handle case where the user does not have access to the JIRA project
8. Delta and Fusion features need to be handled as plugins.
9. Modelling of the link between a KG resource and JIRA issues is assumed to be many-to-many.

**Mockups**
https://docs.google.com/presentation/d/1SNaZnPK6Erh5z6COZv64j8wSDAXp91S4KfZWe92hCFc/edit#slide=id.g10faeb86be8_0_125

**Notes**
* For POC we can write the authentication module in nodejs.
* We can install the trial version of JIRA Server in the developer's local machine for the POC.
* We should try linking the issue from JIRA to Nexus and Nexus to JIRA to validate options for AC 9.

**Comment by dhaneshnm** [comment]
For POC we can write the authentication module in nodejs.

**Comment by samuel-kerrien** [comment]
Link to the JIRA investigation that @imsdu did: #3025

**Comment by dhaneshnm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blue-Brain-Nexus-60ace035034cae00105c9307/issues/BlueBrain/nexus/3039?planning-poker) with ZenHub @samuel-kerrien @imsdu @nicwells

**Comment by imsdu** [comment]
PR for the authentication part for Jira:
https://github.com/BlueBrain/nexus/pull/3127

- I guess we will merge it after the 1.7 release
- The plugin is disabled by default
- There are things missing especially about error handling but it works.
- It is difficult to have tests, I haven't really looked at ways to automate jira start up but it takes forever and consumes a lot of resources
- The jira tokens are stored in a local cache per user for now so whenever Delta is restarted, the token are lost

There are three endpoints for now:
`/v1/jira/request-token` : POST - Allows to perform an authentication request to Jira, will return an url to open so that the user validate it

- No input
- Output:
```{ "value": "https://jira/..."}```

`/v1/jira/access-token` : POST - Allows to pass along the verify code returnedd by Jira when validating the Jira authentication request (must be called after the request token)

- Input:

```{"value": "myCode"}```

- No output (if 200, then it worked and we can )

`/v1/jira/search` : POST - Allows to search Jira issues

- Input:

Same as the Jira api

- Output:

Same as the Jira api if it works
400 if there is no valid token (then we need to call request-token then access-token)
