### ISSUE TITLE
Link to sandbox in tutorial seems to be incorrect

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus#3222]
Link to sandbox in tutorial seems to be incorrectfrom [HERE](https://bluebrainnexus.io/docs/getting-started/try-nexus.html) . It links to 

`https://sandbox.bluebrainnexus.io/web/`

but it should link to 

`https://sandbox.bluebrainnexus.io/`
instead?

![ksnip_20220504-081222.png](https://images.zenhubusercontent.com/62714e29b18ff51479a15c78/8d3c1d3d-0495-4514-a946-e95297a92c6b)

**Comment by samuel-kerrien** [comment]
I think the URL used to be this one, now it seems the landing page of Fusion is `https://sandbox.bluebrainnexus.io/`
@dhaneshnm this probably is the reason for this flickering 404 page when going to the login page.
Is that due to the migration to K8s (@bogdanromanx) or did we change something in Fusion itself ?

**Comment by bogdanromanx** [comment]
Yes, it's related to the k8s migration, I think we just need to update the reference in the docs/tutorials to the new address.

**Comment by samuel-kerrien** [comment]
agreed, but I think if we want to change the URL, we should also have Fusion gracefully redirecting to the landing page from the /web path. users will get a 404 if they have bookmarked the old URL. Same goes for our other BBP deployments.
