### ISSUE TITLE
Data Cart: Download gives error "Download failed" 

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus#3238]
**Describe the bug**

Download from the "Data Cart" gives error "Download failed" (see gif). 400/404 errors in the console

**What part of Nexus is affected**
- [x] Fusion
- [ ] Delta
- [ ] CLI
- [ ] Documentation

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Go to 'Search' (staging)
2. Add some items to the data cart
3. Open the data cart
4. Try to download metadata or data

**Expected behavior**
Download works

**Screenshots**
![May-06-2022 07-37-10.gif](https://images.zenhubusercontent.com/62714e29b18ff51479a15c78/9004f9a0-2933-4ff3-aead-9b7e86f8cc71)

**Additional context**
env: staging
user: adietz

**Comment by bogdanromanx** [comment]
Causes:
1. When downloading an archive the archive metadata is written to disk instead of the actual archive contents
2. An archive cannot be created without any references, so in the case of Download Files when there are no files (no distribution) Delta returns a 400. The operation fails for the user without a clear explanation; the Download Files button should be disabled with a tooltip mentioning why files cannot be downloaded.
