### ISSUE TITLE
Image Plugin: Support images in distribution with a type File or DataDownload

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/nexus#3282]
Please do read the comments first.
The Preview plugin does not support Images, the image plugin does this.
This feedback is valuable though as it shows that the image plugin is not rendering when entities of @type `DataDownload` are in the `distribution`.

### Original Feedback

**Is your feature request related to a problem? Please describe.**

As an end user I expect to see a preview of images, when images are related to an entity. 

For example, the entity at the following link 

https://staging.nise.bbp.epfl.ch/nexus/bbp_test/studio_data_11/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2F1d96556c-e533-4137-bb67-b9595caacd8b

is described as a "PlotCollection", so as an end-user I assume this entity contains a collection of plots/images. 

As this entity has the "Preview" Tab, I expect to see a preview of the images and possibilities to download them. But when I open that "Preview" Tab I see there are 4 images I can download, but I do not see any preview of the images: 

![Screenshot 2022-05-23 at 11.49.40.png](https://images.zenhubusercontent.com/62714e29b18ff51479a15c78/13788174-8653-42cb-8ddd-dafa8b21b4f9)

**Describe the solution you'd like**
As an end-user I expect to have the ability to preview any of these images in the "Preview" tab.

**Additional context**
Env: Staging
User: adietz

**Comment by samuel-kerrien** [comment]
Fair expectations.

We currently support the rendering of images through the Image Viewer plugin.
In this instance, several things are at play:
- We have opted to present the information across several plugins:
  - **image plugin**: for all images. This plugin provides a gallery style presentation so that all images can be looked at at once, instead of requiring download prior to viewing.
  - **preview plugins**: for all data files found under `distribution`. File types like PDF, CSV do have Preview support, not images though. 
- the image plugin expects to find images in one of two locations in the JSON-LD payload of the KG resource:
  - under the property `image`
  - under the property `distribution`, the object should have a `@type` `@File` and a `_mediaType` like `image/*`
  - Now the [current entity](https://staging.nise.bbp.epfl.ch/nexus/bbp_test/studio_data_11/resources/https%3A%2F%2Fbbp.epfl.ch%2Fneurosciencegraph%2Fdata%2F1d96556c-e533-4137-bb67-b9595caacd8b?rev=1#JSON) had indeed 4 image files (_mediaType='image/png') in the `distribution` but they are of type `DataDownload`. 

Conclusion:
- The image plugin should support both @type `File` and `DataDownload`
- It has been planned for the Images plugin to enable downloading of images: #3214
