### ISSUE TITLE
Studio: cannot edit a dashboard's sparql query / query editor behaves oddly

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#3296]
**Description**
Steps to reproduce:
1. Create a studio
2. add a workspace
3. add a dashboard (Sparql view, default SPARQL query)
4. save - all is fine so far
5. edit the dashboard, the editor isn't behaving the same, the cursor doesn't match the query text in the input box. You can try to select text and enter new text, the editing happens in a different place than what you selected. (see video)
6. save your dashboard with a new query
7. open it again - the old query is still there.

![Studio__cannotChangeDashboardQuery.gif](https://images.zenhubusercontent.com/60ad1ee0d2c5ea18af754dc0/981f20e0-10ea-424a-af64-0cc823bfca93)

**Comment by dhaneshnm** [comment]
User has to click on the "Preview" first to save the query, because changing the query will affect the column config. So the bug is not that the save is not working, it is that it is not apparent to the user that preview has to be clicked first.

I propose that we add  tool tip on the save button and disable it unless the user have clicked on the "preview" already.

**Comment by samuel-kerrien** [comment]
The issue originally described doesn't appear to relate to the preview button. We had discussed this and agreed that there was an issue in the component that handles the query editing. 

That issue is still present in Nexus Fusion v1.8.0-M3-1-g03ab697

I am re-opening this ticket.
