### ISSUE TITLE
Redesign proposal for KG resource and data API (wildcard)

### ISSUE THREAD

**Issue by bogdanromanx** [BlueBrain/nexus#332]
The current API for interacting with resources in KG is as follows:

1. Generic form:
   `/v1/resources/{org}/{proj}/{schema_id}/{resource_id}`
2. Schema specific:
   `/v1/schemas/{org}/{proj}/{schema_id}` which is equivalent to:
   `/v1/resources/{org}/{proj}/nxs:shacl-20170720.ttl/{schema_id}`
3. View specific:
   `/v1/views/{org}/{proj}/{view_id}` which is equivalent to:
   `/v1/resources/{org}/{proj}/nxs:view.json/{view_id}`
4. Resolver specific:
   `/v1/resolvers/{org}/{proj}/{resolver_id}` which is equivalent to:
   `/v1/resources/{org}/{proj}/nxs:resolver.json/{resolver_id}`
5. Another endpoint that allows operating on a resource without specifying its schema:
   `/v1/data/{org}/{proj}/{resource_id}`
   (note: this doesn't allow creation of resources because the schema is unknown)

Additionally, there's a specific schema that KG handles in a special way (it doesn't perform validation) which is the `resource` (`nxs:resource.json`) schema, such that when using:
`/v1/resources/{org}/{proj}/resource/{resource_id}`
the system accepts any well formatted json resource without applying shacl validation.

Some of the issues with the current design are:
1. `/v1/data` is confusing to clients because _data_ conveys _everything that's not a schema, view, resolver etc._
2. the `resource` schema is again confusing because there's a forced duplication of the word _resource_ just to maintain compatibility with the API structure

But:
1. getting a resource by id without mentioning its schema is quite useful
2. having the ability to push resources into the system without validation is again very useful

### Proposal

1. Drop the `/v1/data` endpoint for now and consider re-implementing it in `v1.1` (see below section named _second part v1.1_)
2. Handle both cases (getting a resource by id without mentioning a schema and submission of unconstrained resources) through an API wildcard as described below:
(the wildcard `_` means: it's irrelevant, unspecified)

Get a resource from the system without specifying its schema:
`GET /v1/resources/{org}/{proj}/_/{resource_id}`

Create an unconstrained resource:
`PUT /v1/resources/{org}/{proj}/_/{resource_id}`
and additionally, if the resource is in json-ld format (graph transformation yields at least a triple) we can automatically detect or generate an id:
`POST /v1/resources/{org}/{proj}/_` or
`POST /v1/resources/{org}/{proj}`

Listing resources using the wildcard implies listing all resources:
`GET /v1/resources/{org}/{proj}/_` is equivalent to:
`GET /v1/resources/{org}/{proj}`

### Second part (v1.1)

Re-implement `/v1/data` such that it represents the collection of resources that are not schemas, resolvers, views or any other specific Nexus resources:
`/v1/data/{org}/{proj}/{resource_id}`

Creation with id:
`PUT /v1/data/{org}/{proj}/{resource_id}` equivalent to:
`PUT /v1/resources/{org}/{proj}/_/{resource_id}`

Creation with detected or generated id:
`POST /v1/data/{org}/{proj}` equivalent to:
`POST /v1/resources/{org}/{proj}/_` and
`POST /v1/resources/{org}/{proj}` and

Get by id:
`GET /v1/data/{org}/{proj}/{resource_id}` behaves just like:
`GET /v1/resources/{org}/{proj}/_/{resource_id}` __but__ it doesn't match Nexus specific resources (resolvers, views, schemas)

List:
`GET /v1/data/{org}/{proj}` behaves just like:
`GET /v1/resources/{org}/{proj}/_` and
`GET /v1/resources/{org}/{proj}` __but__ it doesn't match Nexus specific resources (resolvers, views, schemas)

**Comment by bogdanromanx** [comment]
I think having a specific endpoint that represents the collection of resources that are not configuration or schemas is quite useful. It represents the user data. While I agree that basic filtering is something we also need, this additional collection handles a very common use case without the need of doing url encoding.
The first part of the proposal address the API inconsistency by removing something from the API and the second one brings back the part that was removed such that it's consistent. I don't feel we're complicating things, but: people that are closer to the users could provide some insights here.
@MFSY @annakristinkaufmann @kenjinp @julienmachon could you share your thoughts on this?

**Comment by mdupont** [comment]
There is clearly a need to distinguish user provided data from other resources that provide support for data (views on the data, resolvers for data ids, schemas for data constraints). v1.0 **should provide a way to list user-provided data** even if it's not as straightforward. How do we go about excluding views, resolvers and schemas from listings?

I like the use of "_", which already has the meaning of "irrelevant" in several programming languages.

I am still unsure about making schemas so prominent, as in making it almost explicit in the URL itself. Why do we keep the form `/v1/resources/{org}/{proj}/{schema_id OR _}/{resource_id}` instead of dropping the schema part altogether? That would open the way for resources that comply to several schemas with no "primary" one. And symbolically it would put schema as an "add-on" for data, with data coming first. Anyways I know there are good reasons, I'd just like to see them stated in the discussion.

**Comment by MFSY** [comment]
Sounds good to me for most of the proposal. I specially like the separation at API level between resources (everything), schemas (for user provided constraints), nexus owned resource types (views, resolvers,  ...) and data (for user provided content that can eventually conform to a schema).

I still don't understand why /v1/data endpoint does not allow submitting a data against a schema.

**Comment by bogdanromanx** [comment]
There's a good reason for having the `{schema_id}` as a required segment in the `/v1/resources` api, namely:
1. we need to know the schema for a resource when creating a schema
2. a very common usecase is listing resources of the same type, for example:
   considering a schema alias {circuits}, one would very much like to be able to do:
   `GET /v1/resources/{org}/{proj}/circuits` to list all resources that are constrained by `circuits`
   resources that conform to a schema become an implicit resource collection

Since resources that conform to the same schema generate an implicit collection, it allows future developments where a resource can conform to multiple schemas at the same time, although schema import addresses that in a more explicit way.

> I still don't understand though why /v1/data endpoint does not allow submitting a data against a schema.
it would require specifying the schema somehow because for `/v1/data` there's no schema segment; we could pass along a query param, but that makes the API a bit inconsistent when we could instead advise the use of `/v1/resources` instead

**Comment by umbreak** [comment]
So, we need the schema segment only for listing and creation.
What if:
1. On listings: query param to filter GET `/v1/resources/{org}/{proj}?schema={id}`
2. On creation: query param to filter POST `/v1/resources/{org}/{proj}?schema={id}`

And for the rest we get rid of the schema segment. This will look like it is consistent
### Get by id
- `/v1/schemas/{org}/{proj}/{id}`
- `/v1/views/{org}/{proj}/{id}`
- `/v1/resources/{org}/{proj}/{id}`
### Create
- `/v1/schemas/{org}/{proj}/{id}`
- `/v1/views/{org}/{proj}/{id}`
- `/v1/resources/{org}/{proj}/{id}?schema={id}`
### List
- `/v1/schemas/{org}/{proj}`
- `/v1/views/{org}/{proj}`
- `/v1/resources/{org}/{proj}` (returns all resources)
- `/v1/resources/{org}/{proj}?schema={id}` (return resources constrained by the given schema {id})

**Comment by bogdanromanx** [comment]
The `/v1/resources` endpoint is a generic one that includes a user specified schema; all the others drop the schema segment for convenience, because it is known.

I'm perfectly comfortable to do this under `/v1/data`, but `/v1/resources` should remain as is for the reasons mentioned [above](https://github.com/BlueBrain/nexus/issues/332#issuecomment-447299927).

**Comment by umbreak** [comment]
The reason being, as you and I mentioned on the comment, **only** important for `create` or `list`. The solution I proposed tackles those cases with query params.

I don't see why `/v1/resources` has to specify the schema, further than for those operations. That's why a query param is better, because it is an optional term.
Note that there is no need at all to have the schema segment for most of operations (even under the `/v1/resources` endpoints):
- tag
- deprecate 
- update

So fixing it just makes the API longer and overcomplicated.

**Comment by mdupont** [comment]
@bogdanromanx are we sure the best way to list things of a given type is through a schema? On the UI side we were repeatedly told that the @type is better suited for this. We're explicitly conflating the concept of a schema to the concept of a type here.

Would resources that conform to multiple schemas have one URL per schema?

**Comment by MFSY** [comment]
`````
are we sure the best way to list things of a given type is through a schema?
````
I think the problem comes with the way the question is specified. As far as schema are concerned, we should talk about accessing resources in a "collection based fashion" as @bogdanromanx pointe out and not listing resources by type.

Listing resources by type should be handled by queries (sparql, ES DSL,...) and I agree with @bogdanromanx  that will not provide guarantees on the shape of the result jsonld payload. I think it is valuable to keep listing resources  by collections (circuits, cars, places, maps, ....) which is a different (but sometimes correlated) from resource types.
