### ISSUE TITLE
Report Plugin: Size tall images appropriately in thumbnail

### ISSUE THREAD

**Issue by nicwells** [BlueBrain/nexus#3393]
Prevent tall images from overflowing their container, see example of issue below

![image.png](https://images.zenhubusercontent.com/60f166b8ed7312d557030820/99a2478f-2eec-47e3-9eab-d49b7975cef6)

# Acceptance criteria
* Images are scaled/clipped appropriately
* Preview overlay displays appropriately when hovering

# Solution proposal:
- Have the width of the image be 100% of its container
- Have a fixed height value
- Center the image in its container
- Hide the overflowing part of the image

# Mockup
![image.png](https://images.zenhubusercontent.com/62c3030fe1d8930ff4e69ab4/23fd5a67-a473-463a-bdc4-b404b43e545d)

**Comment by smitfire** [comment]
Quick question loris. So the grey one (3rd item) is cropped and centered but as you can see the dimensions aren't the same as the previous two images and that is because the previous two images are fitted by width which means the height is smaller than that of our limits. If we followed the same principle and cropped / filled every image to meet our dimensions then we would see every image in view cropped. I don't think this makes much sense since we are partially showing every image in the example below. Any suggestions, ideas?
![Screenshot 2022-08-15 at 12.14.20.png](https://images.zenhubusercontent.com/60f17c1bb2009493eade0339/036e213c-eb76-4fb9-a3f5-180f1161bc9e)
