### ISSUE TITLE
why monix bio

### ISSUE THREAD

**Issue by meittemarc** [BlueBrain/nexus#3404]
Hi,
Just a question.
Why did you remove the Tagless final ? and 
Why use Monix-bio instead of ZIO ?
Thanks

**Comment by bogdanromanx** [comment]
Hello,

We feel that programming in a tagless final style is not well suited for an application because typeclass requirements add a lot of unnecessary noise and at the same time, being more general, do not provide certain functions otherwise present in concrete implementations.
At the time of the switch zio wasn't mature enough, it was quite unstable and we have great confidence in the stability and level of quality of the monix ecosystem.

In the future, please make use of discussions for these kind of q/a.
