### ISSUE TITLE
Project > Browse - When first loading the list of resource, it shows both deprecated and non deprecated

### ISSUE THREAD

**Issue by samuel-kerrien** [BlueBrain/nexus#4010]
## Description
Steps to reproduce:
1. Open a project and deprecate at least one resource
2. open Project > Browse and notice that your deprecated resource is showing up
3. click on the deprecated toggle to only show deprecated resource - that appears to work fine, your deprecated resource can be seen. Toggle again and you only see non deprecated resources.

Expectation: given that the toggle indicates that we are only showing non deprecated resources, the initial resource listing should not show deprecated resources.

**Comment by bilalesi** [comment]
When in this project
https://bbp.epfl.ch/nexus/web/orgs/bbp/mmb-point-neuron-framework-model


I filter for example by 

https://bbp.epfl.ch/ontologies/core/bmo/ModelBuildingConfig


You can see that the resources (without the deprecated ones are 137)
![_thumb_44522.png](https://images.zenhubusercontent.com/63ff6f67213b2c97ca732f08/5b4d434a-6b1c-44be-a3f8-55165a30bde1)
but when I click on that type, it displays all of them, even deprecated so the total amount now is 164.

![_thumb_44523.png](https://images.zenhubusercontent.com/63ff6f67213b2c97ca732f08/c68cedc9-48bb-4aa6-967b-a00ec02d8a02)
Each time that I use the filter I need to check and uncheck the deprecated toggle so I can search over the 137 entries.
![_thumb_44524.png](https://images.zenhubusercontent.com/63ff6f67213b2c97ca732f08/d774995c-296d-4fa9-b4c3-2b2e3161915b)
I would expect that as a default it does not show me the deprecated since the beginning

**Comment by Dinika** [comment]
Fixed in [PR 1379](https://github.com/BlueBrain/nexus-web/pull/1379) which was released in 1.9.6

**Comment by Dinika** [comment]
Fixed in [PR 1379](https://github.com/BlueBrain/nexus-web/pull/1379) which was released in 1.9.6
