### ISSUE TITLE
Allow the deletion of empty organizations

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#4171]
**Motivation**
It is now possible to delete projects.
However, empty orgs can remain and we may want to get rid of them too as they only bring noise in Fusion for example

**Acceptance criteria**
1. Deleting an org can be done via an endpoint
2. A new permission is introduced to be able to delete organizations
3. Project deletion must be enabled
4. The org must not contain any project
5. The acls related to this org must be deleted

**API changes**
```
DELETE
/v1/orgs/my-org
```

**Comment by dantb** [comment]
@imsdu thought it was worth asking since it's not mentioned here - there's already a `DELETE /v1/orgs/my-org?rev=2` endpoint for deprecating an org at a particular revision. Does that change this approach at all? Omitting the rev would be a more destructive operation (though protected by a permission)

**Comment by dantb** [comment]
Also on the database side we have that `deprecated` flag which once set prevents updates to the org - AFAICT here the only difference is that **all** revisions of an org will become `deprecated`?
