### ISSUE TITLE
Support Push notifications from SSE

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#429]
Determine how we could best take advantage of the new Server-Sent Events system in SDK and/or Nexus Web and plan the implementation.

Examples (not necessarily realistic ones):
- Refresh listings whenever a matching resource is updated or created
- Notify of potential conflicts when editing a resource if someone else pushed a new revision while we're on the editing page
- Update the UI / caches depending on changes in the underlying ACLs

**Comment by julienmachon** [comment]
At the moment, we only have SSE on Orgs and Projects. It is quite experimental and the API may change. There a a few things I think we should be aware of:
- We are limited by the max http connections (6 in chrome I think). The way the SSE API is designed right now, it might be an issue
- EventSource (the SSE client in the browser) doesn't not support http headers for some reason, which means we can't provide the Bearer token or Last Event ID to the server. [I've implemented](https://github.com/julienmachon/sse-client) a version of EventSource using the fetch API and streams that also supports headers.

**Comment by bogdanromanx** [comment]
We do also have SSE support for "realms", "permissions" and "acls"; and resource events in kg are coming along this sprint.

Please note that the SSE API is still considered "experimental" (which is why we don't advertise it in the docs). If you're planning on adding this to the JS SDK please mark it accordingly.

We probably need to look at providing event filtering based on permissions to avoid having to open numerous connections to the API. 
Another option would be to support web sockets with an additional backend built for web clients where we can aggregate events for a client using a subscription based protocol... To be discussed.

Another thing to keep in mind is that the number of events may be quite large, especially if we think about KG. Think millions of events at a beginning of the stream.

**Comment by julienmachon** [comment]
Good point, I'll mark it as experimental in the SDK. :+1: 

Let's keep that thread open for future conversations

**Comment by julienmachon** [comment]
This isn't really suitable for direct client side use (as described above, limit of http connections) and should be put behind a socket service. It's a lot of work and we don't really have a good use case for this right now, so I'm closing it
