### ISSUE TITLE
Mismatch between _filename and _location in File resource metadata when special character like [ or ] are present in the file name

### ISSUE THREAD

**Issue by MFSY** [BlueBrain/nexus#4379]
**Describe the bug**
There is a mismatch between _filename and _location property values in File resource metadata when special character like '[' or ']' are present in the file name. For example, a file named "[PH]layer_1.nrrd" is registered: 
- _filename = "[PH]layer_1.nrrd"  
- _location = "file:///.../a/%5BPH%5Dlayer_1.nrrd"
Here is an [example file  resource](https://bbp.epfl.ch/nexus/v1/files/bbp/atlas/https:%2F%2Fbbp.epfl.ch%2Fdata%2Fbbp%2Fatlas%2F5d8d6060-7a11-4166-85c0-a5f69a630f49)
The filename on remote disk is encoded while the value of _filename in the metadata is kept as is. This can cause issues for clients relying on _filename to download the file.

**What part of Nexus is affected**
- [ ] Delta

**To Reproduce**
Steps to reproduce the behavior, e.g. for Fusion:
1. Create a file with name "[PH]layer_1.nrrd" in a project with remote storage configured as default.
2. Check the file metadata

**Expected behavior**
_filename should be equal to the file name on the remote disk

**Comment by olivergrabinski** [comment]
Hi @MFSY , thanks for creating the issue. I will try to summarize what we discussed privately:

* In the metadata the `_location` is assumed to be a valid URI. This means that it does not represent exactly the path on disk; it has to be URL decoded to be able to extract the path on disk.
* This also means that the `_filename` _is_ the filename as it is found on disk.

The recommendation thus would be to decode the `_location`, and from there most libraries will allow you to get the path only, ie the part without the scheme/protocol. This will be the path on disk, and the filename in the path will match the `_filename`.

Having said that, while looking into this I have found that we do have a bug when the `storageType` is `DiskStorage` (local storage). When a filename that is uploaded contains special character, then it is indeed possible that the `_filename` is wrong and does not match what's on disk. This is not an issue with the example you pointed out since it is on a remote stroage. Nevertheless, we'll aim to fix that so that the behavior I described above is valid in all cases.
