### ISSUE TITLE
Refactor ResourceViewContainer

### ISSUE THREAD

**Issue by bilalesi** [BlueBrain/nexus#4541]
## Description
The resource view container component seems getting bigger and bigger and it affect the understanding about each part of the rendered data and also how things can be tested

## Acceptance Criteria

- [ ] Refactor the component to smaller testable components and try to move the state deep down the component that needs it
- [ ] Create stateless component if possible
- [ ] Move queries to use react-query logic when possible
- [ ] Add tests

**Comment by danburonline** [comment]
As context, #4509 raised this issue because the changes made to complete this ticket reduced the coverage below the accepted threshold. To add tests to the `ResourceViewContainer` component, we need to refactor it. The current setup would otherwise make it a difficult task. Therefore, we will merge #4509 now and address this issue (#4541) later.
