### ISSUE TITLE
ConversionError does not lead to a failed elem in composite indexing

### ISSUE THREAD

**Issue by olivergrabinski** [BlueBrain/nexus#4755]
### Description

If we modify the `SparqlClient` to not send a mediatype header in the `sparqlNTriplesResponse` method:

```scala
        val req = Post(endpoint(index), FormData("query" -> q.value))
          // .withHeaders(accept(SparqlNTriples.mediaTypes.toList), additionalHeaders: _*)
          .withHttpCredentials
```

Then when running the `CompositeViewsSpec` integration test, we will see ConversionErrors:

```
2024-02-23 08:13:31 ERROR org.apache.jena.riot - [line: 1, col: 2 ] Expected BNode or IRI: Got: [PREFIXED_NAME:xmlns:owl]
2024-02-23T08:13:31.807949679Z ch.epfl.bluebrain.nexus.delta.rdf.RdfError$ConversionError: Error on the conversion stage 'NTriples to Graph'
2024-02-23T08:13:31.807972304Z Details: [line: 1, col: 2 ] Expected BNode or IRI: Got: [PREFIXED_NAME:xmlns:owl]
```

but if we check the data base we don't see any failed elems in the `composite_offsets` table.

### Additional context

This reproduces an issue where Delta was making requests to Blazegraph through a load balancer. When the load balancer stopped forwarding the mediatype header, the response was not in the NTriple format, leading to a conversion error. The composite views were getting stuck as soon as they encountered the first non-discarded element.

**Comment by imsdu** [comment]
It looks like as the header gets removed, we get back `application/sparql-results+json` so it can't be parsed to `n-triples`
We should test for the content-type in the response before parsing, this way we will get more relevant error messages.

The indexing getting stuck is not really a problem here because the problem comes from an invalid configuration/deployment and not from the resource
