### ISSUE TITLE
Investigate Updating ACLs from ACLs screen

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#481]
Now we can list ACLs, allow users with the right permissions to add / remove ACLs on the current path. When submitting the form, only use API calls to add or subtract permissions, do not use the API call to replace permissions, which is too dangerous.

Among the available permissions, some may be dangerous to enable or remove depending on the path. For these create a "Danger zone" and display a confirmation pop-up message before processing the form.

A couple of permissions may never be disabled because doing so would break the platform entirely (eg the permission to view your own permissions for instance). These should be impossible to disable from the UI, and accompanied by a help text saying what would happen if the permission were to be disabled, and that if a user really wants to do it he has to make a manual call to the REST API.

Depends on #480

**Comment by julienmachon** [comment]
# Managing ACLs

The tricky parts

## Modifying ACLs

Modifying ACLs that have been set on a parent path is hard.
For example, removing read access on a project that has been set at the organisation level involves adding read access to all (projects - the one we are dealing with) before deleting the permission on the `/org` path.

Modifying ACls on a project path is more straight forward.

## Adding ACLs

Adding ACLs on anything but project level is dangerous as it will apply to all children.

It is quite frequent, using the API, that someone replaces ACLs on a path (which has for effect of deleting previous ACLs), rather than `appending` or `subtracting`. Nexus web should assist with that.

## Listing ACLs

You can only list ACLs of a specific path if you have the `acls/view` permission. That means that if you don't have that permission, it is impossible for nexus web to enable permission-based features as you might have the rights to create a new resource, but nexus web cannot see that. Nexus web should display a warning if it cannot list ACLs.

# Guiding the user is key

Nexus web should detect weird and dangerous situations.
For example you can have the `project/write` permission, but not `project/read`, which means you edit a project but you cannot read its content. Nexus web should detect this and display some sort of message or alert to the user (A generic rule could be: if you have `write` or `create` therefore you should have `read`).

When you setup Nexus by default `anonymous` has all permissions on `/`. Nexus web should detect the fact there is no realm and anonymous has permissions on `/` and a message should be displayed, guiding the user into creating a realm.

When the user is logged in, Nexus web should detect that `anonymous` has permissions on `/` and guide the user to replace `anonymous` by their own `user`.

# A potential abstraction on top of ACLs and Permissions

We could come up with 3 distinct groups

## Super admin

a **user** that has the following permissions on `/` (this could be the service account for example):

- `acls/*`
- `permissions/*`
- `realms/*`
- `events/*`
- `projects/*`
- `organizations/ *`
- `resources/*`
- `resolvers/*`
- `views/*`
- `schemas/*`
- `files/*`

## Public access

**anonymous** that have read access on a **project only**:

- `projects/read`
- `resources/read`
- `views/query`
- `schemas/read`
- `files/read`

## Anything in between.

For example:

### Admin

Administrator who can do anything within an organisation.

A **user** or **group** that has the following permissions on an organisation:

- `acls/*`
- `events/*`
- `projects/*`
- `organizations/*`
- `resources/*`
- `resolvers/*`
- `views/*`
- `schemas/*`
- `files/*`

### Project owner

Can do anything within a Project.

A **user** or **group** that has the following permissions on a project:

- `acls/*`
- `events/*`
- `projects/*`
- `resources/*`
- `resolvers/*`
- `views/*`
- `schemas/*`
- `files/*`

### Project Member

Can contribute to a project.

A **user** or **group** that has the following permissions on a project:

- `acls/read`
- `events/*`
- `projects/read`
- `resources/*`
- `views/query`
- `schemas/*`
- `files/*`

**Comment by bogdanromanx** [comment]
Maybe it would be best to consider editing ACLs at the right level instead of doing so from the project view, for example, in the Organization view (where projects are being displayed) we could have a button to open editing the ACLs for that organization and the same when there is no organization selected (to edit the ACLs for root). If there are no `acls/write` at that level the button could be disabled and if there are no `acls/read` the button would not appear.

I strongly believe that introducing roles complicates things because a role is generally opaque. When you look at Admin you don't really see what that means. Neither does public access (is it read-only or read-write)?

I would also consider reversing the way ACLs are being displayed, grouping on access type rather than on Identity type, something like:

**Project:**
me: create / read / write
anonymous: read

**Resources:**
me: create / read / write
authenticated: read

**Schemas:**
me: write

**ACLs:**
me: read / write

This layout would allow displaying the information in a flex table with columns that flow depending on window width.

Next to each section or (identity, permission) pair we could also show if there's a parent definition that would be editable=false and a link to move to that view to change it.

**Comment by mdupont** [comment]
The notion of roles is still useful IMO, since it makes it easier to assign permissions and reason about their consequences, but that's a larger discussion.

The thing about ACLs is that:
1. they apply to any path regardless of whether it exists or not
2. identities are mapped to a unique identifier has no meaning unless we link it back to the corresponding ID provider

Use case provided by @bogdanromanx: allowing a user to create its own personal organisation. It can be achieved with an ACL on its user identity giving the "write organisation" permission on the non-existing path "organisation/[user name]".

It would require careful handling on the UI side to make sure we manage these kinds of use cases correctly (discovering paths from listing user's ACLs, etc).

Also, adding ACLs is tricky since we cannot discover identities from the API at the moment, and it's really suboptimal to ask the user to go discover the string identifier for the corresponding identity in the IAM provider (Keycloak for now), and copy-paste it into a text field.
