### ISSUE TITLE
Make sure that the filename is correctly encoded in the S3 bucket

### ISSUE THREAD

**Issue by imsdu** [BlueBrain/nexus#4941]
**Motivation**
Filenames can sometimes create special characters which are url-encoded.
Akka urls .toString encode them by default and the S3 sdk may encode them a second time

**Acceptance criteria**
1. Make sure that filenames are not url-encoded twice

**Comment by shinyhappydan** [comment]
In order to play this story I would need an example. What is the scenario where this could occur? What should the filename look like on S3?

For example, if the user supplies a filename which is `my file.txt`

What should this look like in nexus? 
- `my file.txt`
- `my%20file.txt` 

Similarly, what should this look like in S3? My current understanding is that only url-encoded strings are allowed, so our options are:
- `my%20file.txt` 
- `urlencode(my%20file.txt)`

It seems as if this ticket is saying that the first option is the correct one, but it's not clear. Perhaps as long as we tell the user the correct path of the file, it doesn't actually matter if the name is double encoded.
