### ISSUE TITLE
Make sure direct links to resources work as expected for users

### ISSUE THREAD

**Issue by mdupont** [BlueBrain/nexus#526]
**Use case:** Data integrators rely a lot on the ability to share direct links to resources on other systems.

The resource may have restricted access, and the user may not be logged in on the web app when clicking.

Make sure that:
- if the resource is not public and the user not logged-in, display the login form. After logging-in, the user should be redirected to the original URL link of the resource
- if the user does not have permission to see the resource while she's logged-in, display an error page with a meaningful message ("you don't have permission to see this content" and something about how to ask for access)

**Comment by julienmachon** [comment]
This has been implemented for projects, but not resources

**Comment by julienmachon** [comment]
If an unauthenticated used lands on a protected resource, the following message is displayed:
![Screenshot from 2019-11-26 11-13-18](https://user-images.githubusercontent.com/4364154/69620519-c9a05980-103d-11ea-9f0f-f6071956dd0c.png)

Same thing happens when landing on any other views, appart from Sparql/ES and ACLs views.

The 2 bullet point above are still valid

**Comment by adulbrich** [comment]
Probably related in Sentry: https://sentry.io/organizations/blue-brain-project/issues/1384024839/events/735b9a114fd84dde8f3386de7de29e65/?project=1845930
