### ISSUE TITLE
When using SSE there is not enough information to exercise the API

### ISSUE THREAD

**Issue by umbreak** [BlueBrain/nexus#598]
This issue summaries a request from @olinux and makes some proposals for a solution:

Using SSE in kg resources you get back the projectUUID and the resource ID information. However, our API does not support to use the projectUUID on the URI (/v1/resources/{projUUID}/_/{resourceID}).

There are several solutions:
1. On the admin service, add a lookup endpoint: `/v1/projects/_/{projectUUID}/lookup`
2. On the kg service support both labels and UUIDs `/v1/resources/{orgUUID}/{projectUUID}/_/{resourceId}`
In this case, we have to add the organizationUUID to the SSE (which we have to add anyway in order to support SSE per organization).
3. On the kg service support both labels and UUIDs, with the character `_` for the organizationUUID `/v1/resources/_/{projectUUID}/_/{resourceId}`

Some other suggestions are welcomed.

**Comment by wwajerowicz** [comment]
I think that since the UUID uniquely identifies the project we could simplify the API call to `/v1/resources/{projectUUID}/_/{resourceId}`. In this case we wouldn't need to add the `organizationUUID` to the SSE for this use case.

**Comment by umbreak** [comment]
I updated the first comment to include @wwajerowicz option, but keeping the API segments consistent

**Comment by olinux** [comment]
I agree that (since the project determines the organization), the comment of @wwajerowicz is valid for the (technical) resolution of the resource. The information about the organization would be interesting in SSEs nevertheless, since we make use of it for dispatching. Not providing it in the SSE would mean, that we need to resolve the project first to extract the organization information. Adding it to the SSE therefore would simplify our code a lot and I can imagine other consumers of the SSE might be interested in this kind of information as well.

**Comment by bogdanromanx** [comment]
I agree that adding this information to the events would be very useful. With respect to the API, I think we can efficiently handle UUIDs in the segments and I generally like the idea of using `_` as a wildcard for cases where the organization is not needed:
`/v1/resources/_/{project_uuid}/_/{resource_id}`
`/v1/projects/_/{project_uuid}`
`/v1/orgs/{org_uuid}`
etc.
When the wildcard is not used, we can check if the provided organisation and project match correctly. I have mixed feelings about the use of mixed labels and uuids, but since they do not pose a technical challenge or feature ambiguity we can allow them.

**Comment by umbreak** [comment]
@olinux the final solution has been the following:
1. Added `_organizationUuid` to the Events through SSE
2. Added the possibility the exercise the APIs using UUIDs or labels indistinguishably

Those two items should fix your issues.
