### ISSUE TITLE
Compare project resources side by side

### ISSUE THREAD

**Issue by dhaneshnm** [BlueBrain/nexus#805]
Add ability to view to view resources in a project side by side.

@annakristinkaufmann

**Comment by adulbrich** [comment]
@annakristinkaufmann could you provide a use case for this please?

**Comment by annakristinkaufmann** [comment]
Hi @adulbrich ! I am afraid I don't remember the exact reason for this request. I think at the time, there was not yet the full studio capability available and I was looking for a way to see metadata of multiple resources from one project at the same time (since the only way at the time was to click on a resource and see the detailed view). With the table view in studios, I think this issue is no longer relevant. Let me know what you think!

**Comment by adulbrich** [comment]
@adulbrich thank you for the details! I guess tables provide a good alternative indeed! Now, what about the ability to see the differences between two resources? I'm thinking along the lines of "Files Changed" in Github. Where you can compare the actual JSONs and see what was added/removed in the RAW text?

**Comment by annakristinkaufmann** [comment]
Hi @adulbrich  ! That sounds like a nice feature to have :) I am regularly using the "History" tab to see changes between different revisions of a JSON payload.
