### ISSUE TITLE
Studio: Custom components #2

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#909]
Using **static build**.

- Document
- Prototype
- Pros/cons

**Comment by kenjinp** [comment]
## PROS
- Consistent API, same code stack as react-nexus, for example.
- Code splitting ensures that the browser is not overloaded with content it doesn’t need
- Faster than eval or iframe
- Easy for developers to implement, as simple as developing any other package

## CONS
- Not compatible with private plugin code, strictly limited to open source plugins, otherwise our build system and such wouldn’t work. 
- Requires rebuilding and changing the source code to test and build. Users of nexus with other instances who want to use their own packages would have to fork nexus-web and apply their plugin libraries, build, and redeploy
