### ISSUE TITLE
Create an empty Shacl Schema for studio

### ISSUE THREAD

**Issue by julienmachon** [BlueBrain/nexus#946]
We need to make sure our studio resources are contrained by a Schema. The schema can be empty for now and implemented later. 

But in nexus, we cannot changed the `_constrainedBy` value after a resource a created.

**Comment by kenjinp** [comment]
@umbreak Recommends that we manage these schemas in a special project, something like the `neurosciencegraph/datamodels`, and make sure to include a `Cross-Project Resolver` in each project that uses a studio. Putting the `Studio Context` there is also recommended, instead of making one in each project. 

further questions:

- Should we maintain these schemas in the nexus-web github repo?
- What project should they be inside, especially for prod environments?
- How do we bootstrap this studio datamodels project for dev or staging environments

**Comment by kenjinp** [comment]
We should maintain these schemas inside the nexus-web github repo under `/schemas`, for example. 

Eventually, they should be tested either using a test suite and schema validator or via integration tests during the CI process. 

We'll ask the backend buddies to add these schemas and contexts to a special org/project to be bootstrapped when the instance is initialised, name TBD

**Comment by kenjinp** [comment]
Closed for now because we don't want to add the maintenance cost of creating projects and populating them with app-specific schemas. Nexus Web is a core part of the Nexus stack and it would be a shame to have Nexus Web features broken if certain schemas are not integrated out of the box. 

I think having some special `Resolver` fetch the schemas from the `nexus-web` repo would be a better solution
