### ISSUE TITLE
Show "name" or "label" on graph nodes

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus#960]
Right now, the children in the graph view only show the `@id` as a label. It would be better to show the `name` or `label` property if available. 

feedback from @alegrm

**Comment by adulbrich** [comment]
@MFSY @annakristinkaufmann  We had feedback from CAMH that they would like to see the rdfs:label on the graph for internal nodes instead of the uuid. Could you provide some input for the best logic for display? First check label, then schema, then uuid for example?

**Comment by bogdanromanx** [comment]
Maybe this could be a project configuration stored as a resource in Nexus, with a reasonable default. I presume people may have different preferences.

**Comment by MFSY** [comment]
Hi. @adulbrich 

>...see the rdfs:label on the graph for internal nodes instead of the uuid.

Are you talking about displaying by default the value of rdfs:label instead of a UUID for a **Nexus resources in Nexus Web** ?

If yes then it is reasonable to always look for a human readable label to display for a resource. 
The usual label properties widely used out there are:

- rdfs:label
- skos:prefLabel
- schema:name

There are many others, but we can start by these. Here are a good read about this from the [Linked Data Patterns book](https://patterns.dataincubator.org/book): 

[ label-everything ](https://patterns.dataincubator.org/book/label-everything.html)
[ preferred-label ](https://patterns.dataincubator.org/book/preferred-label.html)


I recommend to combine these defaults (the app will look for them by default) with enabling the user to change the defaults by setting which properties to use when listing a given resource as 
@bogdanromanx proposed.

**Comment by kenjinp** [comment]
duplicate of #https://github.com/BlueBrain/nexus/issues/913
